### ISSUE TITLE
Pose largely drift

### ISSUE THREAD

**Issue by YangSiri** [hku-mars/FAST_LIO#1]
Hi, @XW-HKU 

I compiled Fast-LIO in ubuntu16.04 and I tried to test it with Avia. But the result may be totally wrong, I'm curious about what I may have done to make this kind of strange phenomenon?

![2020-12-12 11-33-33](https://user-images.githubusercontent.com/33154113/101973144-c0962080-3c70-11eb-9082-96b8a32e4c8b.png)

The pose may drift even thought it is still.

Looking forward to your help  ;>

**Comment by XW-HKU** [comment]
1. Which launch file you use?
2. Please make sure the version of pcl and ubuntu meet the requirements writen in the project readme.

**Comment by YangSiri** [comment]
> roslaunch fast_lio mapping_avia.launch
> roslaunch livox_ros_driver livox_lidar_msg.launch

I try to test it on ubuntu16.04 with default pcl. I see the system runs normally without any errors but the result is strange. 
I was running real time. I will record some bag and send to you later. Thanks for your answer!

**Comment by YangSiri** [comment]
Hi, @XW-HKU 

The _2020-12-12-18-10-36_aviaTest.bag_ has been sent to your email.

**Comment by XW-HKU** [comment]
Here are three thing may help you:
1. The Avia LiDAR cannot produce good measurement inside the 10m distance between surroundings and liDAR
2. FAST_LIO only support ubuntu >= 18.04 and pcl >= 1.8, please look at the homepage of this github repo.
3. In the bag you sent me, FAST LIO can work well at the first 11s, but after 11s, the lidar is staying before a wall closer than 2m, which will make the liDAR produce meaningless points.

**Comment by YangSiri** [comment]
Thanks, @XW-HKU 

You mean the bag works normally in your environment which is 18.04 except the situation you mentioned?

**Comment by YangSiri** [comment]
Thanks, @XW-HKU
