### ISSUE TITLE
Multiple Lidars support

### ISSUE THREAD

**Issue by raspectedward** [hku-mars/FAST_LIO#100]
May we know if this supports multiple Horizon Lidars? Thanks

**Comment by AHuguetUPC** [comment]
The algorithm itself does not care where does the pointcloud come from, so it would be pretty direct to do!

Have you tried adding an additional subscriber calling the same callback, given the timestamps correctly I guess it should work. It's actually an interesting try...

Andreu

**Comment by raspectedward** [comment]
so do you mean I just give out the combined rosbag from multiple Horizon lidars. The algorithm should work?

**Comment by XW-HKU** [comment]
> so do you mean I just give out the combined rosbag from multiple Horizon lidars. The algorithm should work?

if you make sure the extrinsics and timestamps are all right，that should work.

**Comment by raspectedward** [comment]
we tried FAST LIO with multiple lidars. It first generates the integrated map then change to pcd. The map generation part has errors when more than one lidar.
