### ISSUE TITLE
About memory usage

### ISSUE THREAD

**Issue by Psyclonus2887** [hku-mars/FAST_LIO#102]
Thank you for your excellent work! The algorithm performs better than LIO_SAM in our dataset in off-road scenes, while I have some problem in memory usage. When using LIO-SAM, the memory usage is around 1%, but when using FAST-LIO2, memory usage is around 13.9%, in the same dataset around 200s. The pcd_save_en parameter is set to false, but it seems whether it is true or false, the usage of memory is equal. I also tried to adjust the cube_side_length parameter, it didn't make any difference. Is that a question led by the using of ikd-tree to organize local map?

**Comment by XW-HKU** [comment]
Did you try to close the rviz, since the rviz will save all the points in the memory.

**Comment by Psyclonus2887** [comment]
The memory usage is calculated when rviz is turned off. I use htop to check the mem usage of different thread

**Comment by Psyclonus2887** [comment]
And the memory usage is growing when the map gets larger

**Comment by XW-HKU** [comment]
I think the 10% - 20% consumption is normal and the local map size is constrained by the cube_side_length. Such that the memory consumption will grow to a certain point and now too much.

**Comment by Psyclonus2887** [comment]
I agree that in theory the memory usage should be constrained by cube_side_length, but when I adjust this parameter, the mem usage just keep growing, and I am sure the map size is larger than the cube size

**Comment by Psyclonus2887** [comment]
I output the size of kd-tree and map num when running the code, finding that the two number keeping growing through the whole procedure. I am sure the cube size is properly settled, it seems like the remove of map points is failed. Do you have any idea about it?

**Comment by Psyclonus2887** [comment]
Another phenomenon is the kdtree_delete_counter is always 0

**Comment by Ecstasy-EC** [comment]
@Psyclonus2887  
Sorry for the late reply. The number of valid tree nodes on ikd-Tree is maintained in the `valid_num()` which is very different from the tree size. Those deleted points are firstly deleted by attaching an tag on it ('deleted' label). They will be deleted during the rebuilding process when it is necessary. Further details could be achieved in our papaer. We also provide an example about this phenomenon in the ikd-Tree repo. 

The boxwise delete function will be trigged when you are moving close to the edge of the local map. We have tested this function in ikd-Tree repo for many times. But I am not sure if there is bug for this. If possible please provide more details or data for this.

**Comment by Ecstasy-EC** [comment]
@Psyclonus2887 
Any updates about the memory usage?

**Comment by Ecstasy-EC** [comment]
This issue is closed for no more updates. 
Thanks~

**Comment by jukindle** [comment]
@Ecstasy-EC I notice this issue, too. The memory usage just keeps growing even with the sensors static. After an hour or so, fast_lio crashes due to being out of memory on my machine with 64GB RAM. Would you have a suggestion how I could add a memory limit to the algorithm?

**Comment by jukindle** [comment]
> > @Ecstasy-EC I notice this issue, too. The memory usage just keeps growing even with the sensors static. After an hour or so, fast_lio crashes due to being out of memory on my machine with 64GB RAM. Would you have a suggestion how I could add a memory limit to the algorithm?
> 
> Could you please have a look at the size of ikd-tree?

After 10 mins or so

tree size: 19440
tree valid num: 17432

**Comment by jukindle** [comment]
x-axis is time [s], y-axis is number of entries [1] (red is the size of the kdtree, blue is the number of valid entries in the kdtree)
on average, the memory consumption of fast_lio grows at about 19MB/s. This plot was created with the sensor being static

![image](https://github.com/hku-mars/FAST_LIO/assets/32697515/1000a394-e773-4840-8ad7-21e108c34549)

**Comment by jukindle** [comment]
@Ecstasy-EC I just realized that I was on the wrong trail, if I use your stock implementation my memory does not grow insanely as it does with ours. We branched out from fast lio lc which seems to be the cause of the issues. Will switch back to your standard implementation, thanks a lot for your help!

**Comment by Ecstasy-EC** [comment]
> I have the same issue, but i could not understand how you solved it? @Ecstasy-EC 

Check the PCD save param in the config file first.

Btw, please open another issue and mention me there again if the solution above cannot work.
