### ISSUE TITLE
请教一下，代码中重力加速度一项对应的S2是什么意思？

### ISSUE THREAD

**Issue by yuhui-xie** [hku-mars/FAST_LIO#106]

**Comment by yuhui-xie** [comment]
以及
		enum
		{
			n = state::DOF,
			m = state::DIM,
			l = measurement::DOF
		};
DOF和DIM在这个包里含义如何？
比如说state是一个SO3的话，那么DOF是3，DIM是9吗？还是说DIM也是3？

**Comment by Joanna-HE** [comment]
S2是一种空间，一个确定半径的球面构成的空间就被称作2-sphere，也叫S2，DOF指的是对应类型空间的维数，SO3是3维，DOF等于3，DIM指的是用于改变对应空间内状态变量时的外部扰动的维度，旋转角速度可以改变SO3的状态量，所以SO3的DIM是3。另外，DIM和DOF会在S2上有区别，S2的维度是2维，所以DOF等于2，S2的状态变量也是用旋转角速度改变的，所以S2的DIM与SO3相同，是3。

**Comment by yuhui-xie** [comment]
> S2是一种空间，一个确定半径的球面构成的空间就被称作2-sphere，也叫S2，DOF指的是对应类型空间的维数，SO3是3维，DOF等于3，DIM指的是用于改变对应空间内状态变量时的外部扰动的维度，旋转角速度可以改变SO3的状态量，所以SO3的DIM是3。另外，DIM和DOF会在S2上有区别，S2的维度是2维，所以DOF等于2，S2的状态变量也是用旋转角速度改变的，所以S2的DIM与SO3相同，是3。

感谢
