### ISSUE TITLE
IMU offset on  Livox Horizon and  loosing track

### ISSUE THREAD

**Issue by mohsenhadadi** [hku-mars/FAST_LIO#108]
Hi everyone 
When I use Fast-Lio for Livox Horizon mounted at a 90 degrees perpendicular to my IMU's Y axis ,I encountered the following errors that I have attached. Please explain a little more about the parameters that I highlighted
, I only encounter such a problem when I change livox angle related to my IMU angle downwards among Y axis ,
anybody can help me solving this problem??

![config2](https://user-images.githubusercontent.com/96223813/146664773-f13cbb4e-0c6b-4960-82b7-9596d966809d.JPG)
![scan](https://user-images.githubusercontent.com/96223813/146664775-5437749a-9bc1-41eb-a325-b46c8e535644.JPG)
![Untitled](https://user-images.githubusercontent.com/96223813/146664776-71b3b001-8116-4df2-bfc9-f315031f77ef.png)

**Comment by XW-HKU** [comment]
Why dont you use insider IMU of horizon and trouble yourself.

**Comment by mohsenhadadi** [comment]
Thanks for your response, but even when I use livox internal IMU and turn livox downward around Y axis the same problem will occur

**Comment by XW-HKU** [comment]
> Thanks for your response, but even when I use livox internal IMU and turn livox downward around Y axis the same problem will occur

make sure there is no degeneration when you turn lidar downward.

**Comment by mohsenhadadi** [comment]
> 

What do you mean by degeneration?
Why when I change its location and direction due to my IMU in other axises rather than Y, it is fine and I don't have any error. But when misalignment is around Y and 90 degrees downward this problem happens , Can you please explain degeneration for me

**Comment by XW-HKU** [comment]
> Thanks for your response, but even when I use livox internal IMU and turn livox downward around Y axis the same problem will occur

WHAT DO YOU MEAN "turn livox downward around Y" when you use internal imu ???????

**Comment by mohsenhadadi** [comment]
Look I have tried 2 different setups:
1st: using horizon + Fast Lio+ external IMU

2nd: using horizon and its internal IMU + Fast Lio 

In both situation when livox is looking downward  from my multirotor I get errors and generated points are not in correct position
But if I install It in forward looking position on my multirotor every thing is fine

**Comment by XW-HKU** [comment]
If lidar is facing only one big surface like ground. It cannot locate itself.

**Comment by mohsenhadadi** [comment]
It was an interesting point 
Thank you so much for taking the time to help solve my problem

**Comment by mohsenhadadi** [comment]
Excuse me, I had a few more questions, can you help me?
Why should scan_line in Horizon config. File be 6 while horizon is not a linear LiDAR and it has a wide non-repetitive pattern?
And what about other parameters in the mapping file except extrinsics , do we need really to change them?

**Comment by XW-HKU** [comment]
> Excuse me, I had a few more questions, can you help me? Why should scan_line in Horizon config. File be 6 while horizon is not a linear LiDAR and it has a wide non-repetitive pattern? And what about other parameters in the mapping file except extrinsics , do we need really to change them?

Actually the line number is not used in the livox lidar handler function.

**Comment by mohsenhadadi** [comment]
Thank you so much
