### ISSUE TITLE
avia特征提取原理介绍

### ISSUE THREAD

**Issue by chenxianbo** [hku-mars/FAST_LIO#110]
avia特征提取原理有介绍文档吗，希望能在其基础修改适配MID70

**Comment by XW-HKU** [comment]
为什么一定要提取特征？

**Comment by chenxianbo** [comment]
还是想对比下特征法与直接法，你们的特征法与之前livox_mapping的特征法。

**Comment by chenxianbo** [comment]
我目前用你们算法，适配的mid70，但特征一直没有适配，想适配看一下效果。

**Comment by XW-HKU** [comment]
特征提取没有文档，很早之前做的，早就不维护了。

**Comment by chenxianbo** [comment]
最老的版本也行，我就是有几处没看懂，能发我邮箱吗

**Comment by XW-HKU** [comment]
> 最老的版本也行，我就是有几处没看懂，能发我邮箱吗

我是说这个代码是很早之前开发的，没有文档，现在也不维护了。

**Comment by chenxianbo** [comment]
好的，谢谢回复
