### ISSUE TITLE
About ikd-tree

### ISSUE THREAD

**Issue by Psyclonus2887** [hku-mars/FAST_LIO#111]
I found that the radius-search function is not embedded in your ikd-tree as a public function and the same function is available in pcl's kd-tree. Do you have plan to add the function in the future? Another question is, I notice the code in the nearest point judgement, there is possibility the knn search can return points less than five, even when the searching radius is set to INFINITY, which kind of makes me curious.

**Comment by Huguet57** [comment]
I think they are about to release the radius-search function or is already released: https://github.com/hku-mars/ikd-Tree/commit/6bc08351d57fbd990c80e80377224296129acb4b.

**Comment by Psyclonus2887** [comment]
Thanks, it seems it has been merged but just hasn't been released.

**Comment by Psyclonus2887** [comment]
> I think they are about to release the radius-search function or is already released: [hku-mars/ikd-Tree@6bc0835](https://github.com/hku-mars/ikd-Tree/commit/6bc08351d57fbd990c80e80377224296129acb4b).

And BTW have you encountered the case that failing to delete points by PointBox? It seems when I run FAST_LIO2 the delete function doesn't work and the kd-tree size keeps growing.

**Comment by Ecstasy-EC** [comment]
@Psyclonus2887 
Could you please provide me any bags or data that you observed those weird phenomenon about ikd-Tree?

**Comment by Psyclonus2887** [comment]
> @Psyclonus2887 Could you please provide me any bags or data that you observed those weird phenomenon about ikd-Tree?

Thx, I will reply you tomorrow with some log

**Comment by Psyclonus2887** [comment]
@Ecstasy-EC
I test FAST-LIO in the ros bag of nclt dataset you released. 
<img width="581" alt="image" src="https://user-images.githubusercontent.com/57947526/147451130-92a557c6-1434-47f1-9bb0-1981a59b94e6.png">
<img width="566" alt="image" src="https://user-images.githubusercontent.com/57947526/147451331-c83d8d0b-6468-4eba-9be5-5996be7ebeb0.png">
I show two screen prints here in different time of this bag when running the code, where:
cub_needrm size is the output of cub_needrm.size()
need remove cube number i is cub_needrm[i].vertex_min and cub_needrm[i].vertex_max
points deleted num is kdtree_delete_counter in your code
kdtree_size is ikdtree.size()

**Comment by Ecstasy-EC** [comment]
> @Ecstasy-EC I test FAST-LIO in the ros bag of nclt dataset you released. <img alt="image" width="581" src="https://user-images.githubusercontent.com/57947526/147451130-92a557c6-1434-47f1-9bb0-1981a59b94e6.png"> <img alt="image" width="566" src="https://user-images.githubusercontent.com/57947526/147451331-c83d8d0b-6468-4eba-9be5-5996be7ebeb0.png"> I show two screen prints here in different time of this bag when running the code, where: cub_needrm size is the output of cub_needrm.size() need remove cube number i is cub_needrm[i].vertex_min and cub_needrm[i].vertex_max points deleted num is kdtree_delete_counter in your code kdtree_size is ikdtree.size()

The vertices of the boxes to be removed seem quite weird. Did you change the launch file and the yaml file? What is value of the param `cube_side_length` in the launch file and `DET_RANGE`?

**Comment by Psyclonus2887** [comment]
cube_side_length is set to 20, and DET_RANGE is set to 100

**Comment by Ecstasy-EC** [comment]
> cube_side_length is set to 20, and DET_RANGE is set to 100

Local map size(i.e., cube_size_length) should always be larger than the two times of the DET_RANGE. Pls refer to our paper about the working principle of local map management. Never change the parameters until you are sure how they work.

**Comment by Psyclonus2887** [comment]
I will try it and read the paper again. Thanks a lot!!!
