### ISSUE TITLE
Question about saving PCD files

### ISSUE THREAD

**Issue by hallyx** [hku-mars/FAST_LIO#112]
I found that after 30min scanning by the Avia, the PCD file only records the last 10min the point cloud file. Is there anything to solve this problem？

**Comment by XW-HKU** [comment]
I dont know

**Comment by EloyAldao** [comment]
There is an option to divide the PCD output (-1 makes only one file, so can break) I think that it is in the config y'all, not in the launch file
I also split the bags I record every 2Gb to avoid corruption

**Comment by PengKunPROO** [comment]
@EloyAldao Hi, I have a question about what value you set to the parameter "interval". If I set 10 to the interval,for which means I split the pcd file every 10 seconds?
Best wishes!waiting for your reply!

**Comment by Tomato1107** [comment]
> @EloyAldao Hi, I have a question about what value you set to the parameter "interval". If I set 10 to the interval,for which means I split the pcd file every 10 seconds? Best wishes!waiting for your reply!

interval不是你认为的间隔时间，给interval赋大于1的值是指最后生成pcd的个数。看代码pcd应该是程序最后退出的时候才生成
