### ISSUE TITLE
KITTI dataset error "Failed to find match for field 'time'."

### ISSUE THREAD

**Issue by GreatEms** [hku-mars/FAST_LIO#115]
Thank you for your bravo contribution!
I tried the http://www.cvlibs.net/datasets/kitti/raw_data.php KITTI dataset with https://github.com/tomas789/kitti2bag tool to transfer the Synchronized IMU and velodyne to rosbag. I followed the Readme to edit yaml file, then played the kitti rosbag with error  "Failed to find match for field 'time'."  I wondered why Synchronized IMU failed, and how to run the KITTI rosbag properly.
I am really looking forward to your reply.

**Comment by Huguet57** [comment]
This is an error of the ``POINT_CLOUD_REGISTER_POINT_STRUCT``, are you using this type?

``POINT_CLOUD_REGISTER_POINT_STRUCT(velodyne_ros::Point,``
``    (float, x, x)``
``    (float, y, y)``
``    (float, z, z)``
``    (float, intensity, intensity)``
``    (float, time, time)``
``    (std::uint16_t, ring, ring)``
``)``

**Comment by Sunshinehaozi** [comment]
So far as I know,the data of HDL-64 in kitti dataset dose not have timestamp field

**Comment by Shubham-2302** [comment]
@GreatEms Were you able to solve it ?

**Comment by lijing137** [comment]
> @GreatEms Were you able to solve it ?

Have you solved this problem?

**Comment by hankyeolyu** [comment]
Have you solved this problem?

**Comment by Huguet57** [comment]
> This is an error of the `POINT_CLOUD_REGISTER_POINT_STRUCT`, are you using this type?
> 
> `POINT_CLOUD_REGISTER_POINT_STRUCT(velodyne_ros::Point,` ` (float, x, x)` ` (float, y, y)` ` (float, z, z)` ` (float, intensity, intensity)` ` (float, time, time)` ` (std::uint16_t, ring, ring)` `)`

It's probably this thing, guys

**Comment by hankyeolyu** [comment]
> > 이것은 오류입니다 `POINT_CLOUD_REGISTER_POINT_STRUCT`. 이 유형을 사용하고 계신가요?
> > `POINT_CLOUD_REGISTER_POINT_STRUCT(velodyne_ros::Point,` ` (float, x, x)` ` (float, y, y)` ` (float, z, z)` ` (float, intensity, intensity)` ` (float, time, time)` ` (std::uint16_t, ring, ring)` `)`
> 
> 아마 이거일 거야, 얘들아

So should I modify the Point struct definition to fix this?
