### ISSUE TITLE
Hi, I've got a  pcd issus

### ISSUE THREAD

**Issue by Minsu-Kim-KNU** [hku-mars/FAST_LIO#117]
Hi, I'm try to fast_LIO with MID-70 and IMU with intel realsense D435i.

I just followed all steps in this repository, but in my rviz viewr, I cannot see any points. any solutions?
![Screenshot from 2022-01-12 15-05-24](https://user-images.githubusercontent.com/97087039/149073349-8c06df51-ada4-4d6b-88a0-e8fe200a5deb.png)
)

**Comment by seeeheng** [comment]
Perhaps you could check under "Global Status: Error" what the error is. It's likely to be a frame issue.
