### ISSUE TITLE
Add ROS2 support

### ISSUE THREAD

**Issue by ItsJas** [hku-mars/FAST_LIO#120]
Hi,
Do you have any plans to port the package to ros2?

**Comment by borongyuan** [comment]
Hi,
I'm porting this project to ros2.
https://github.com/borongyuan/FAST_LIO/tree/ros2
It's nearly finished but not yet tested.
Thanks

**Comment by Tomato1107** [comment]
> I meet some compile errors on ros2 Foxy.
![621221ff9613f3b6b1da62a7ef3d6f2](https://user-images.githubusercontent.com/19368992/152258411-4573b669-1cc8-405b-8d18-03db3ce959c7.jpg)

**Comment by borongyuan** [comment]
Looks like these are just warnings, we'll see if we can get rid of them later.

**Comment by XW-HKU** [comment]
> Hi, I'm porting this project to ros2. https://github.com/borongyuan/FAST_LIO/tree/ros2 It's nearly finished but not yet tested. Thanks

Thankyou very much！

**Comment by Tomato1107** [comment]
> Looks like these are just warnings, we'll see if we can get rid of them later.

Finally I compile the ros2 version without errors, are there any lanuch.py files?
