### ISSUE TITLE
Livox Horizon closed loop mapping has drifting problem

### ISSUE THREAD

**Issue by DannyRaspect** [hku-mars/FAST_LIO#121]
Location: Carpark

Lidar model: Livox horizon lidar ( just use built-in imu )

Record command: rosbag record -a 

I want to ask it is the slam config or hardware lend to the drift result?

![1](https://user-images.githubusercontent.com/97510928/151752682-5a267e68-633e-4ac3-a67d-65f1f2e12519.png)
![2](https://user-images.githubusercontent.com/97510928/151752786-cae7b2ef-eab6-4544-a47b-f4f889c44e74.png)
![3](https://user-images.githubusercontent.com/97510928/151752854-a0ec2934-e8c5-4e23-af45-371745fed0d9.png)

**Comment by kxch928925819** [comment]
你可以试着采用以人为轴心的左右摆动式扫描来试试！我也用horizon，地下车库是成果最后的地方！

**Comment by liunao123** [comment]
很奇怪，程序启动的时候，如果一直往一个方向运动，轨迹的 Z 值会一直增大，大概 0.1m/s ，然后反方向回来的话，Z 值会逐渐减小，大概 -0.1m/s 。回到原点，差不多会变成0，范围越大，回到原点的误差就越大。请指点一下可能是啥原因，感谢。
