### ISSUE TITLE
Hi, I have an issue when using my Velodyne-VLP-16 lidar.

### ISSUE THREAD

**Issue by jhforstudy** [hku-mars/FAST_LIO#128]
Hi, thanks for your great code.

I'm using ubuntu 18.04 & velodyne VLP-16 lidar.
I downloaded your package and rosbag file (I also used what you gave. HDL-32E rosbag file.)
I checked it has no problem with the rosbag file.
But, I tried to use my velodyne VLP-16 lidar instead of the rosbag file,

This error message comes:
"Failed to find match for field 'time'."

As you said, I think the timestamp is missing, but I don't know what to do.
I googled it and read velodyne manual too... but I failed.
Can you give me a help? I'm really looking forward to your answer.

**Comment by arjunskumar** [comment]
@jhforstudy you need to set the point type of your lidar as XYZIRT

**Comment by jhforstudy** [comment]
@arjunskumar Thank you for your answer! You mean that I have to publish XYZIRT, not XYZIR? Ok I’ll try it.

**Comment by arjunskumar** [comment]
@jhforstudy yes

**Comment by arjunskumar** [comment]
@jhforstudy are you able to fix the issue?

**Comment by jhforstudy** [comment]
Yes @arjunskumar, my Velodyne topic doesn't have time stamp, that was the problem.
You can close this issue. Thanks.

**Comment by MoonSheepJx** [comment]
> 

hello, i meet the same question about timestamp of velodyne16. 
I want to know velodyne16 simply cannot publish the timestamp of every point.
Or is it possible to set something of velodyne16 to enable the lidar to publish points with timestamp?

**Comment by mteastepp** [comment]
@MoonSheepJx the velodyne driver that is installed using `apt install ros-x-velodyne` does not publish the point-wise timestamps. You need to pull the latest driver directly from the github page, then it will publish the point-wise timestamp.
