### ISSUE TITLE
Rviz configuration

### ISSUE THREAD

**Issue by qiuyu09130408** [hku-mars/FAST_LIO#13]
Hello, I would like to ask you how the topic was configured in the fixed frame and pointclouds in RVIZ when you made the drawing. I did not find the poingcloud data
thank you for your answer

**Comment by kxch928925819** [comment]
去年7月，我试LIVOX-MAPPING 时，做过一点研究，基本思路是rosbag转pcd 然后在用PCL-viewer转出point-cloud。 看目前这个情况，FAST-LIO可以直接在在程序中开启pointcloud输出，后者直接输出LVX，然后采用cloudcompare 2.1.1 直接打开 *.lvx,如果需要las，在pcd、lvx都可以转las。
