### ISSUE TITLE
Loop back之后系统停止

### ISSUE THREAD

**Issue by XinZhaoDC** [hku-mars/FAST_LIO#131]
我采用的是***avia***传感器，在测试数据时出现了loop back的报错，同时建图系统停止。请问这个问题应该怎么解决？
下面是相关截图：
![Uploading issue1.jpg…]()
![Uploading issue2.jpg…]()
![Uploading issue3.jpg…]()
![Uploading issue4.jpg…]()

**Comment by XinZhaoDC** [comment]
![issue1](https://user-images.githubusercontent.com/52630624/158023858-f61d7d86-a03c-47e5-98d2-8e35ec562835.jpg)
![issue2](https://user-images.githubusercontent.com/52630624/158023862-bbde3eff-f652-49b7-bd70-8602921f605a.jpg)
![issue3](https://user-images.githubusercontent.com/52630624/158023865-2aa74a3e-e9eb-4992-b20f-b74225804829.jpg)
![issue4](https://user-images.githubusercontent.com/52630624/158023870-68a007e2-6378-41af-b3c1-4affd30f1640.jpg)

**Comment by XW-HKU** [comment]
大概率是IMU数据时间戳在某个时刻错乱了。

**Comment by XinZhaoDC** [comment]
> 大概率是IMU数据时间戳在某个时刻错乱了。

谢谢，所以针对这种问题，有没有什么解决方法呢？只能换数据了么？
