### ISSUE TITLE
Incorrect timestamp_unit for Velodyne config

### ISSUE THREAD

**Issue by kennyjchen** [hku-mars/FAST_LIO#132]
In `config/velodyne.yaml`, `timestamp_unit` should be `0` since Velodyne pointwise timestamps are in seconds, not microseconds. Thanks.

**Comment by Ecstasy-EC** [comment]
Thanks for your notice. The default time unit is set according to our tested datasets. You could modify it to fit your applications.

**Comment by XW-HKU** [comment]
Different velodyn datesets have different time unit. You should carefully check it before you test any code or datesets.

**Comment by kennyjchen** [comment]
Understood, thanks very much.

FYI for all -- the official ROS driver for Velodyne sensors timestamps points in units of seconds:
https://github.com/ros-drivers/velodyne/blob/master/velodyne_pointcloud/src/lib/rawdata.cc#L655
