### ISSUE TITLE
Issue about The formula(18)

### ISSUE THREAD

**Issue by onionysy** [hku-mars/FAST_LIO#136]
我在您的论文里看到，在卡尔曼滤波更新部分，您得出的状态更新公式（论文中的公式18）与一般的更新公式不同，能请问下您是怎么推导出来的吗 
<img width="261" alt="捕获" src="https://user-images.githubusercontent.com/55376216/159197238-6bc3a62f-e7a1-4229-81ad-b36145bd6466.PNG">
?

**Comment by XW-HKU** [comment]
这一块比较复杂，请参考我们的文章 https://arxiv.org/abs/2102.03804

**Comment by inntoy** [comment]
> 你之前看到的常规卡尔曼滤波都是在笛卡尔坐标系下的实数域上推导的，如果系统状态中有旋转矩阵这种manifold上的状态，则update方程需要变化。这一块比较复杂，请参考我们的文章 https://arxiv.org/abs/2102.03804

您好，我看到你们引用的另一篇工作(LINS)里状态更新的公式和公式18不一致（它们也是迭代误差卡尔曼滤波）。然后我发现公式18广义加号右边括号里的那部分，其实就是误差状态的更新。这样公式18相比于LINS文章里的状态更新公式就有一个好处：迭代过程中误差状态的均值一直为0，这样每次更新和观测方程都可以在原点处线性化，请问我这样理解对吗？

**Comment by inntoy** [comment]
@bugdeveloper0 抱歉，我最近在做其他的工作，已经有段时间没有看推导，相关公式忘的差不多了，可能没办法给你提供工作了。

**Comment by HViktorTsoi** [comment]
> 我在您的论文里看到，在卡尔曼滤波更新部分，您得出的状态更新公式（论文中的公式18）与一般的更新公式不同，能请问下您是怎么推导出来的吗 <img alt="捕获" width="261" src="https://user-images.githubusercontent.com/55376216/159197238-6bc3a62f-e7a1-4229-81ad-b36145bd6466.PNG"> ?

请看 **Kalman Filters on Differentiable Manifolds** 的公式(38), **Performance evaluation of iterated extended Kalman filter with variable step-length**的公式(14, 19, 20)，以及**The Iterated Kalman Filter Update as a Gauss—Newton Method**的section V

**Comment by inntoy** [comment]
您好，您的邮件我已收到。————祝您每天都有个好心情!
