### ISSUE TITLE
scan_line and blind Parameters

### ISSUE THREAD

**Issue by Angleoo** [hku-mars/FAST_LIO#137]
Hi all,

I am curious about the scan_line and blind parameters in the config file. 
What are these parameters for? And what values should I set them to?

Thank you!

**Comment by arjunskumar** [comment]
@Angleoo scan_line : resolution of your lidar, for ex; scan_line for vlp-16 is 16, and blind is the region removed from the processed pointcloud, this is required to remove the robot body,  in other words, all the lidar points inside the blind are removed
