### ISSUE TITLE
realsense d455 相机集成的IMU和LPMS-IG1 RS232 IMU 报错terminate called after throwing an instance of 'std::runtime_error'   what():  Time is out of dual 32-bit range

### ISSUE THREAD

**Issue by kismet999** [hku-mars/FAST_LIO#139]
你好，感谢你们开源这么好的作品。
我分别使用镭神c16和速腾聚创c16这两种雷达分别配合realsense d455 相机集成的IMU和LPMS-IG1 RS232 IMU
尝试建图，但是出现了如下图的报错
请教一下可能是什么问题。谢谢！！
错误截图如下：

![2022-03-23 16-42-58屏幕截图](https://user-images.githubusercontent.com/94662127/159659424-52d77c16-3b62-4cf7-8fec-2b32678fe110.png)

ubuntu的版本如下：
![2022-03-23 16-50-04屏幕截图](https://user-images.githubusercontent.com/94662127/159660036-2fcb0796-ce20-43e6-a879-52a8b64df82d.png)
尝试过使用
速腾聚创的C16的激光雷达
![2022-03-23 17-12-23屏幕截图](https://user-images.githubusercontent.com/94662127/159664624-ffb4dbb7-1778-4bb6-800a-c0b06c7991e6.png)
和
镭神C16激光雷达

外接的IMU尝试使用过
intel的
realsense d455 集成的imu
![IMG20220323171905](https://user-images.githubusercontent.com/94662127/159665800-5ba2704e-c425-49f7-8d3b-043112f3bf05.jpg)

和
LPMS-IG1 RS232
两种：

![IMG20220323170853](https://user-images.githubusercontent.com/94662127/159665615-45f5c349-4379-48a1-8d9b-6e7613c3cc15.jpg)

尝试过网络上很多解决上述问题的方法，但是都没有成效

**Comment by XW-HKU** [comment]
建议先好好研究一下IMU和雷达之间的时间同步怎么做。

**Comment by piedaochuan1234** [comment]
我也遇到同样的报错，根据代码找到是因为输入点云没有滤除无效点。希望有帮助。

**Comment by inntoy** [comment]
@piedaochuan1234 yaml文件里的blind参数是用来消除距离小于blind大小的点，因为velodyne里面无效点坐标是0,0,0，所以如果用velodyne跑算法其实是滤除了无效点

**Comment by inntoy** [comment]
您好，您的邮件我已收到。————祝您每天都有个好心情!

**Comment by MA-xiaowen** [comment]
所以请问这个问题是怎么被解决的呢？

**Comment by inntoy** [comment]
您好，您的邮件我已收到。————祝您每天都有个好心情!

**Comment by PigletPh** [comment]
大佬，请问我在镭神雷达与IMU标定时，出现Failed to find match for field 'time'. 同时出现Compute offset time using constant rotation model问题，请问怎么回事，谢谢

**Comment by inntoy** [comment]
您好，您的邮件我已收到。————祝您每天都有个好心情!
