### ISSUE TITLE
超核HI226

### ISSUE THREAD

**Issue by yandld** [hku-mars/FAST_LIO#140]
您好，我是北京超核电子 Alex。
看到您有用我司的产品，非常感谢！
如需其他高精度型号的话，我们免费提供样品。可以加我wechat 15701256050

**Comment by yandld** [comment]
HI226

**Comment by Ecstasy-EC** [comment]
> HI226

我们工作中并未使用贵司的产品，仅另一ISSUE中有提及，请直接在其issue下回复。该issue关闭，谢谢。
