### ISSUE TITLE
浙大lidar imu标定成果 如何才能写做velodyne yaml

### ISSUE THREAD

**Issue by kxch928925819** [hku-mars/FAST_LIO#142]
[calib_result0328.csv](https://github.com/hku-mars/FAST_LIO/files/8377120/calib_result0328.csv)

mapping:
    acc_cov: 0.1
    gyr_cov: 0.1
    b_acc_cov: 0.0001
    b_gyr_cov: 0.0001
    fov_degree:    180
    det_range:     100.0
    extrinsic_est_en:  false      # true: enable the online estimation of IMU-LiDAR extrinsic,
    extrinsic_T: [ 0, 0, 0.28]
    extrinsic_R: [ 1, 0, 0, 
                   0, 1, 0, 
                   0, 0, 1]

**Comment by Ecstasy-EC** [comment]
读懂对应csv数据含义后，自行对应数据类型输入即可

**Comment by zyx-99** [comment]
想问您的IMU是lord品牌的吗

**Comment by Ecstasy-EC** [comment]
> 想问您的IMU是lord品牌的吗

不同数据集用的IMU不一样，请参考我们文章里给出的信息

**Comment by zyx-99** [comment]
> > 想问您的IMU是lord品牌的吗
> 
> 不同数据集用的IMU不一样，请参考我们文章里给出的信息

十分感谢您的回复，我查看了您的文章，发现使用是Xsens M TIG 710的IMU，我现在手中的是与LIO SAM同款的IMU 3dm gx5 25
![image](https://user-images.githubusercontent.com/103629575/164594037-b1782ac6-8feb-43b9-9692-fb0062408906.png)
但此款IMU的XYZ轴对应的ROLL PITCH YAW貌似与Xsens不同（与雷达不对应），那是不是就无法跑通FAST-LIO呢。

**Comment by Ecstasy-EC** [comment]
> > > 想问您的IMU是lord品牌的吗
> 
> > 
> 
> > 不同数据集用的IMU不一样，请参考我们文章里给出的信息
> 
> 
> 
> 十分感谢您的回复，我查看了您的文章，发现使用是Xsens M TIG 710的IMU，我现在手中的是与LIO SAM同款的IMU 3dm gx5 25
> 
> ![image](https://user-images.githubusercontent.com/103629575/164594037-b1782ac6-8feb-43b9-9692-fb0062408906.png)
> 
> 但此款IMU的XYZ轴对应的ROLL PITCH YAW貌似与Xsens不同（与雷达不对应），那是不是就无法跑通FAST-LIO呢。

LIO-SAM的数据集我们是能跑的，但需要自行设置好外参。imu和雷达之间外参准确的情况下可以正常运行

**Comment by zyx-99** [comment]
> 哈哈，我郁闷的有两个，第一 3dm-gx3-25的数据频率是100hz 我在琢磨给它改成200hz 第二 用浙大的计算lidar imu 结果 不太好 也就是标定的参数误差太大 第三 用了lidar align 标定 结果也不好 出现漂移很大 所以在考虑是不是问题在第一个上 数据频率太低 &nbsp;
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: ***@***.*** ***@***.***&gt; 发送时间: 2022年4月22日 13:21 收件人: hku-mars/FAST_LIO ***@***.***&gt; 抄送: Weiguo Zhao ***@***.***&gt;, Author ***@***.***&gt; 主题: 回复：[hku-mars/FAST_LIO] 浙大lidar imu标定成果 如何才能写做velodyne yaml (Issue #142) 想问您的IMU是lord品牌的吗 不同数据集用的IMU不一样，请参考我们文章里给出的信息 十分感谢您的回复，我查看了您的文章，发现使用是Xsens M TIG 710的IMU，我现在手中的是与LIO SAM同款的IMU 3dm gx5 25 但此款IMU的XYZ轴对应的ROLL PITCH YAW貌似与Xsens不同（与雷达不对应），那是不是就无法跑通FAST-LIO呢。 LIO-SAM的数据集我们是能跑的，但需要自行设置好外参。imu和雷达之间外参准确的情况下可以正常运行 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

方便留个邮箱交流一下嘛

**Comment by kxch928925819** [comment]
***@***.*** 向你学习




------------------ 原始邮件 ------------------
发件人: ***@***.*** ***@***.***&gt;
发送时间: 2022年4月29日 13:34
收件人: hku-mars/FAST_LIO ***@***.***&gt;
抄送: Weiguo Zhao ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[hku-mars/FAST_LIO] 浙大lidar imu标定成果 如何才能写做velodyne yaml (Issue #142)





  
哈哈，我郁闷的有两个，第一 3dm-gx3-25的数据频率是100hz 我在琢磨给它改成200hz 第二 用浙大的计算lidar imu 结果 不太好 也就是标定的参数误差太大 第三 用了lidar align 标定 结果也不好 出现漂移很大 所以在考虑是不是问题在第一个上 数据频率太低 &nbsp;
 …
 ------------------ 原始邮件 ------------------ 发件人: @.*** @.&gt; 发送时间: 2022年4月22日 13:21 收件人: hku-mars/FAST_LIO @.&gt; 抄送: Weiguo Zhao @.&gt;, Author @.&gt; 主题: 回复：[hku-mars/FAST_LIO] 浙大lidar imu标定成果 如何才能写做velodyne yaml (Issue #142) 想问您的IMU是lord品牌的吗 不同数据集用的IMU不一样，请参考我们文章里给出的信息 十分感谢您的回复，我查看了您的文章，发现使用是Xsens M TIG 710的IMU，我现在手中的是与LIO SAM同款的IMU 3dm gx5 25 但此款IMU的XYZ轴对应的ROLL PITCH YAW貌似与Xsens不同（与雷达不对应），那是不是就无法跑通FAST-LIO呢。 LIO-SAM的数据集我们是能跑的，但需要自行设置好外参。imu和雷达之间外参准确的情况下可以正常运行 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
方便留个邮箱交流一下嘛

**Comment by kxch928925819** [comment]
名字中的数字就是QQ邮箱号码！还是没搞定，希望能得到你的指导啊！

**Comment by zfc-zfc** [comment]
> 

雷达IMU外参标定可以参考我们的新工作 LI-Init: https://github.com/hku-mars/LiDAR_IMU_Init

**Comment by wangchuanhao1231** [comment]
> 名字中的数字就是QQ邮箱号码！还是没搞定，希望能得到你的指导啊！

请问你搞定了吗，我也在学习怎么把标定的结果写进yaml文件中。
