### ISSUE TITLE
initialization

### ISSUE THREAD

**Issue by Torchmm** [hku-mars/FAST_LIO#143]
感谢您的出色工作：
在初始化过程中，我看到初始化了bg, gravity, init_P,还有外参。但是没有初始化ba。是没法得到一个比较好的ba吗？ 在我的测试中，当某个方向出现退化时，我保持静止，但里程计还是很快飘走。现在我看到代码中没有退化检测，我想像loam一样加上退化检测，退化方向只用imu的预测，不进行更新，但是初始化的时候退化方向没有初始化ba，所以也无法得到一个相对准确的预测。所以初始化的时候，ba不便于估计出来吗？

**Comment by ZikangYuan** [comment]
额，我不是作者，但是ba确实是可以估计的，我也做过LiDAR-IMU的联合初始化，具体估计ba的方法可以参考ORB-SLAM3，把当中视觉提供的位姿观测换成雷达ICP计算的就行了

**Comment by Torchmm** [comment]
@ZikangYuan 嗯，现在它们初始化方式不一样，FAST_LIO是静置估计的。现在假设是在视觉或者雷达的退化环境中，他们目前是估计了重力方向和陀螺仪偏差，如果我已知IMU是不动的，这种情况下能估计出加速度计偏差吗？

**Comment by zfc-zfc** [comment]
> 

IMU静止，加速度偏移(bias_a)和重力耦合，肯定是初始化不了的。必须给予足够的激励，可以参考我们最近的工作 LI-Init (https://github.com/hku-mars/LiDAR_IMU_Init).

**Comment by Torchmm** [comment]
@zfc-zfc 好的，谢谢 ，已关注！
