### ISSUE TITLE
What is the role of these parameters?

### ISSUE THREAD

**Issue by Xu-Huitong** [hku-mars/FAST_LIO#149]
What is the role of these parameters? 
param name="filter_size_corner" type="double" value="0.2" 
param name="filter_size_surf" type="double" value="0.2" 
param name="filter_size_map" type="double" value="0.5" 
"runtime_pos_log_enable" type="bool" value="1"
"cube_side_length" type="double" value="2000"

**Comment by rlabs-oss** [comment]
The pointcloud is down sampled and corner and surface features are created as landmarks used during the ICP / scan registration - the filter_size_corner/surface is the volume for the detector(s) with the filter_size_map being the filter applied to the point cloud before insertion to the global map. - at least according to my understanding.
