### ISSUE TITLE
Global status: warn, No tf data received

### ISSUE THREAD

**Issue by syang94** [hku-mars/FAST_LIO#151]
Hello! 
When command 'roslaunch fast_lio mapping_velodyne.launch' , rviz shows "Global status: warn, No tf data received", then I open the VLP16 lidar , command 'roslaunch velodyne_points VLP16.launch', issue still exits, rviz has no map data. What's the problem of this? Anyone can help me?
Many thanks!

**Comment by lxystar00** [comment]
I have the same question, How did you solve this? Thank you
