### ISSUE TITLE
IMU z Axis drift in a closed loop scan

### ISSUE THREAD

**Issue by mohsenhadadi** [hku-mars/FAST_LIO#155]
Hello friends,
I have a livox horizon integrated with jetson xavier nx and an adis16470 imu data from " CUAV X7 Pro"  ,
and using PTP time synchronizing method.
Problem 1 : when scanner installed on a car roof and scanning a level area I have no problem and everything is fine
BUT the problem is when I scan an area with different elevations  and in the result point cloud and  the start points do not Mach the end points and it seems like it had a drift in z axis or not sensing street elevation correctly.
How can I fix it? is it IMU problem or synchronizing problem?

thank you for your answering...

**Comment by rlabs-oss** [comment]
This is normal, FAST_LIO does not perform loop closure.

**Comment by rlabs-oss** [comment]
normal problem due to drift - fast_lio does not loop close.
