### ISSUE TITLE
Doubt on Lidar - IMU calibration

### ISSUE THREAD

**Issue by srinivasrama** [hku-mars/FAST_LIO#165]
How to find the extrinsic relation between  lidar and IMU?
Also how to find IMU intrinsic parameters?

**Comment by rlabs-oss** [comment]
same question - is translation even supported?

**Comment by zfc-zfc** [comment]
> How to find the extrinsic relation between lidar and IMU? Also how to find IMU intrinsic parameters?
Our recent work LI-Init is recommended: https://github.com/hku-mars/LiDAR_IMU_Init.
