### ISSUE TITLE
Process has dies during playing the data

### ISSUE THREAD

**Issue by knurgazy** [hku-mars/FAST_LIO#170]
I am using ouster lidar os1-128. When I use "rosbag play my_file.bag", I face this problem. 
`[laserMapping-2] process has died [pid 38057, exit code -11, cmd /home/ubuntu/A_ROS_DIR/devel/lib/fast_lio/fastlio_mapping __name:=laserMapping __log:=/home/ubuntu/.ros/log/54920bae-f201-11ec-9999-6d259b2401ed/laserMapping-2.log].
log file: /home/ubuntu/.ros/log/54920bae-f201-11ec-9999-6d259b2401ed/laserMapping-2*.log
`

**Comment by shahaizi0** [comment]
请问解决了吗？我也遇到了这个问题 @knurgazy

**Comment by huangyoupingben** [comment]
ikd_tree 初始化后，在插入点云的函数 add_points 时候，程序出现崩溃。点云已经做过异常值检查，没有nan 和 inf 等异常情况。 gdb捕获到的信息，如下图所示：
![1](https://user-images.githubusercontent.com/61875969/232773780-ffba8c1e-5489-4436-a7de-1607f727f7b1.png)
![2](https://user-images.githubusercontent.com/61875969/232773831-d401e2ab-483c-4800-8c33-ee7a1fadfa23.png)

**Comment by autel-liuxiaozi** [comment]
> I am using ouster lidar os1-128. When I use "rosbag play my_file.bag", I face this problem. `[laserMapping-2] process has died [pid 38057, exit code -11, cmd /home/ubuntu/A_ROS_DIR/devel/lib/fast_lio/fastlio_mapping __name:=laserMapping __log:=/home/ubuntu/.ros/log/54920bae-f201-11ec-9999-6d259b2401ed/laserMapping-2.log]. log file: /home/ubuntu/.ros/log/54920bae-f201-11ec-9999-6d259b2401ed/laserMapping-2*.log `

solved？this problem also occured in my situation

**Comment by autel-liuxiaozi** [comment]
> 请问解决了吗？我也遇到了这个问题 @knurgazy

我也遇到了，请问怎么解决

**Comment by autel-liuxiaozi** [comment]
解决了，源代码没有这个问题。但我们是修改过的代码所以有问题。将pcd点云输出到了其他路径，然后却又没有创建那个目录，导致出错

**Comment by yuafowo** [comment]
> 解决了，源代码没有这个问题。但我们是修改过的代码所以有问题。将pcd点云输出到了其他路径，然后却又没有创建那个目录，导致出错

你好 我想请教一下 适配ouster128的时候，总是出现漂移的情况，还有''[WARN][1731321809.915177231]: No point, skip this scan!",你有遇到过这种情况嘛

**Comment by hzlbbfrog** [comment]
> > 解决了，源代码没有这个问题。但我们是修改过的代码所以有问题。将pcd点云输出到了其他路径，然后却又没有创建那个目录，导致出错
> 
> 你好 我想请教一下 适配ouster128的时候，总是出现漂移的情况，还有''[WARN][1731321809.915177231]: No point, skip this scan!",你有遇到过这种情况嘛

你好，请问你解决了吗，我也是漂移然后提示这个问题。我是ouster64，我怀疑是config的问题，但是不知道正确的config呢

**Comment by yuafowo** [comment]
> > > 解决了，源代码没有这个问题。但我们是修改过的代码所以有问题。将pcd点云输出到了其他路径，然后却又没有创建那个目录，导致出错
> > 
> > 
> > 你好 我想请教一下 适配ouster128的时候，总是出现漂移的情况，还有''[WARN][1731321809.915177231]: No point, skip this scan!",你有遇到过这种情况嘛
> 
> 你好，请问你解决了吗，我也是漂移然后提示这个问题。我是ouster64，我怀疑是config的问题，但是不知道正确的config呢

解决了在preprocess.cpp文件的ouster_handler函数中过滤掉nan点，即在循环中添加“if(isnan(pl_orig.points[i].x) || isnan(pl_orig.points[i].y) || isnan(pl_orig.points[i].z)) continue;” 希望可以帮助到你。

**Comment by Ratarang** [comment]
> ikd_tree 初始化后，在插入点云的函数 add_points 时候，程序出现崩溃。点云已经做过异常值检查，没有nan 和 inf 等异常情况。 gdb捕获到的信息，如下图所示： ![1](https://user-images.githubusercontent.com/61875969/232773780-ffba8c1e-5489-4436-a7de-1607f727f7b1.png) ![2](https://user-images.githubusercontent.com/61875969/232773831-d401e2ab-483c-4800-8c33-ee7a1fadfa23.png)

Hey bro, have you fixed your mentioned problem?
