### ISSUE TITLE
请教外参标定问题

### ISSUE THREAD

**Issue by InterKnight** [hku-mars/FAST_LIO#174]
你好，感谢开源此优秀项目。
请问如果我将多个雷达的输出合并到一个topic中，并用这个topic进行建图，那我该如何确定Lidar和IMU之间的外参呢？

**Comment by InterKnight** [comment]
感谢解答，[LiDAR_IMU_Init]中的标定过程需要3个方向的有效激励，如果没办法执行某些方向的激励的话，请问有没有其他办法

**Comment by Ecstasy-EC** [comment]
如果激励不充分的话，或许可以尝试一下[OA-LICalib](https://github.com/APRIL-ZJU/OA-LICalib)。但这个方法我们也没有实测过，不确定好不好使

**Comment by InterKnight** [comment]
非常感谢！
