### ISSUE TITLE
What is the relationship between the curvature of the point cloud and time？

### ISSUE THREAD

**Issue by LiquoriceH** [hku-mars/FAST_LIO#175]
Hi，
in the func of “**bool sync_packages(MeasureGroup &meas)**” ，
lidar_end_time = meas.lidar_beg_time + **meas.lidar->points.back().curvature / double(1000)**;
Why curvature divided by 1000 is the interval time？

**Comment by XW-HKU** [comment]
the unit of curvature is ms, not s.

**Comment by LiquoriceH** [comment]
> the unit of curvature is ms, not s.

Thank for your explaination.
But I mean that why the unit of curvature is time? It should be m^-1.

**Comment by XW-HKU** [comment]
> > the unit of curvature is ms, not s.
> 
> Thank for your explaination. But I mean that why the unit of curvature is time? It should be m^-1.

I just reuse this variable.

**Comment by LiquoriceH** [comment]
> > > the unit of curvature is ms, not s.
> > 
> > 
> > Thank for your explaination. But I mean that why the unit of curvature is time? It should be m^-1.
> 
> I just reuse this variable.

Can you explain it in detail? I still don't understand why the curvature divided by 1000 is the scan interval time, I don't think curvature and time are related.
Thank you very much!

**Comment by XW-HKU** [comment]
> > > > the unit of curvature is ms, not s.
> > > 
> > > 
> > > Thank for your explaination. But I mean that why the unit of curvature is time? It should be m^-1.
> > 
> > 
> > I just reuse this variable.
> 
> Can you explain it in detail? I still don't understand why the curvature divided by 1000 is the scan interval time, I don't think curvature and time are related. Thank you very much!

I just use the curvature variable to save the timestamp, please refer to the preprocess.cpp to check how the curvature is used to save the timestamp.

**Comment by LiquoriceH** [comment]
> > > > > the unit of curvature is ms, not s.
> > > > 
> > > > 
> > > > Thank for your explaination. But I mean that why the unit of curvature is time? It should be m^-1.
> > > 
> > > 
> > > I just reuse this variable.
> > 
> > 
> > Can you explain it in detail? I still don't understand why the curvature divided by 1000 is the scan interval time, I don't think curvature and time are related. Thank you very much!
> 
> I just use the curvature variable to save the timestamp, please refer to the preprocess.cpp to check how the curvature is used to save the timestamp.

Oh，I see. Thank you for your patience!

**Comment by LiquoriceH** [comment]
Thank for your explaination.
But I mean that why the unit of curvature is time? It should be&nbsp;m^-1.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hku-mars/FAST_LIO"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月25日(星期一) 上午10:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [hku-mars/FAST_LIO] What is the relationship between the curvature of the point cloud and time？ (Issue #175)





 
the unit of curvature is ms, not s.
