### ISSUE TITLE
localization and loop closure problem

### ISSUE THREAD

**Issue by mohsenhadadi** [hku-mars/FAST_LIO#176]
Dear Friends, 
I am using the latest release of this project from https://github.com/hku-mars/FAST_LIO.git and updated it using
 git submodule update --init    .
**My setup is :** 
Livox horizon sensor
 + Cuav X7 pro(used as IMU and reading through MAVROS) 
+ CUAV C-RTK (connected to X7pro) 
+ Jetson Xavier NX 8GB embedded computer
+ time synchronization is the software type by using ( time_sync_en: true )

**The problems I have got:**
1- when lidar faces ground or a big wall the scan will be corrupted (localization problem)
2- I have loop-closing problem  and the loop is not closed!
3- I can not set scan rate more than 10 hz and when I use more frequency the Rviz and my computer will be hanged-out and not respond. 
4- I wand my point-cloud to be Geo-referenced with RTK data and how should I do it?

any help will be much appreciate

**Comment by rlabs-oss** [comment]
1. set the blind value lower, default is 4 meters "blind: 4" 
2. fast_lio does not loop close this is normal. 
3. try faster_lio with rviz:=false to create the scans.pcd file (headless / no rviz)
