### ISSUE TITLE
Config file after calibration

### ISSUE THREAD

**Issue by ManChrys** [hku-mars/FAST_LIO#181]
Hello guys and thanks again for the great projects.

After i use [LiDAR_IMU_Init](https://github.com/hku-mars/LiDAR_IMU_Init) i got the initialization.txt 

Refinement result:
Rotation LiDAR to IMU (degree)     = 1.920841 0.100224 0.280654
Translation LiDAR to IMU (meter)   =  0.018073 -0.065269  0.149609
Time Lag IMU to LiDAR (second)     = 1661782715.179687

on `extrinsic_T:` i put the 0.018073 -0.065269  0.149609
on `time_offset_lidar_to_imu:` i put the 1661782715.179687
but how can i put the rotation data to ` extrinsic_R` so i can have the matrix in a correct format ? Should be a [3x3] table like in the example or just like txt [1x3] table?

Thanks in advance.

**Comment by zfc-zfc** [comment]
> table
 initialization.txt of LiDAR-IMU_Init would give both rotation matrix and Euler angles. FAST-LIO needs rotation matrix format, which is a 3x3 matrix.

**Comment by zfc-zfc** [comment]
> translation

That's correct.

**Comment by zfc-zfc** [comment]
> 

Both correct. The quote is automatically generated by github.
