### ISSUE TITLE
Odometry Covariance 

### ISSUE THREAD

**Issue by vislero** [hku-mars/FAST_LIO#185]
Hello!

I have some questions about publish odometry message and covariance.

1. Is there any reason that ```odomAftMapped```  published before the covariance is defined? 
https://github.com/hku-mars/FAST_LIO/blob/a56a0c544ae305e9b00ca4cd4e262d20703fdaa8/src/laserMapping.cpp#L585
 
2. And the covariance is defined in the code below, why is the order of covariance(position, orientation) reversed in this part?
https://github.com/hku-mars/FAST_LIO/blob/a56a0c544ae305e9b00ca4cd4e262d20703fdaa8/src/laserMapping.cpp#L593

3.  Is the covariance ```P``` also set according to the definition order in the code below? So, is ```P(12,12) to P(14,14)``` the covariance for velocity state, depending on the order of definition?
https://github.com/hku-mars/FAST_LIO/blob/a56a0c544ae305e9b00ca4cd4e262d20703fdaa8/include/use-ikfom.hpp#L12

Regards

**Comment by Pallav1299** [comment]
@vislero, I am also trying to add velocity data in output with convariance. Were you able to figure out which components of output covariance matrix (from get_P) constitute the same?
