### ISSUE TITLE
QObject::connect: Cannot queue arguments of type 'QVector<int>' (Make sure 'QVector<int>' is registered using qRegisterMetaType().)

### ISSUE THREAD

**Issue by ManChrys** [hku-mars/FAST_LIO#186]
geo@geo:/media/geo/d057a6b6-f590-4870-a4f8-13b392d0f9eb/geo/ws_livox$ roslaunch fast_lio mapping_avia.launch 
... logging to /home/geo/.ros/log/ea126236-2e7f-11ed-9430-00012e910c4a/roslaunch-geo-30351.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://geo:40117/

SUMMARY
========

PARAMETERS
 * /common/imu_topic: /imu/data
 * /common/lid_topic: /livox/lidar
 * /common/time_offset_lidar_to_imu: 0.0
 * /common/time_sync_en: True
 * /cube_side_length: 1000.0
 * /dense_publish_enable: True
 * /feature_extract_enable: False
 * /filter_size_map: 0.5
 * /filter_size_surf: 0.5
 * /mapping/acc_cov: 0.1
 * /mapping/b_acc_cov: 0.0001
 * /mapping/b_gyr_cov: 0.0001
 * /mapping/det_range: 260.0
 * /mapping/extrinsic_R: [0.999817, -0.018...
 * /mapping/extrinsic_T: [-0.220601, -0.08...
 * /mapping/extrinsic_est_en: False
 * /mapping/fov_degree: 38.4
 * /mapping/gyr_cov: 0.1
 * /max_iteration: 8
 * /pcd_save/interval: -1
 * /pcd_save/pcd_save_en: True
 * /pcd_save_enable: True
 * /point_filter_num: 3
 * /preprocess/blind: 2
 * /preprocess/lidar_type: 1
 * /preprocess/scan_line: 6
 * /publish/dense_publish_en: True
 * /publish/path_en: False
 * /publish/scan_bodyframe_pub_en: True
 * /publish/scan_publish_en: True
 * /rosdistro: melodic
 * /rosversion: 1.14.13
 * /runtime_pos_log_enable: False
 * /scan_publish_enable: True

NODES
  /
    laserMapping (fast_lio/fastlio_mapping)
    rviz (rviz/rviz)

ROS_MASTER_URI=http://localhost:11311

process[laserMapping-1]: started with pid [30373]
/media/geo/d057a6b6-f590-4870-a4f8-13b392d0f9eb/geo/ws_livox/devel/lib/fast_lio/fastlio_mapping: /usr/local/lib/libtiff.so.5: no version information available (required by /usr/lib/x86_64-linux-gnu/libvtkIOImage-6.3.so.6.3)
process[rviz-2]: started with pid [30374]
/opt/ros/melodic/lib/rviz/rviz: /usr/local/lib/libtiff.so.5: no version information available (required by /usr/lib/x86_64-linux-gnu/libfreeimage.so.3)
Multi thread started 
p_pre->lidar_type 1
~~~~/media/geo/d057a6b6-f590-4870-a4f8-13b392d0f9eb/geo/ws_livox/src/FAST_LIO/ file opened
[ INFO] [1662557962.921190100]: IMU Initial Done
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
^C[rviz-2] killing on exit
[laserMapping-1] killing on exit


Hello guys,

i have the following message when i run the launch file. Its probably something about Qt, but how can i fix it ?

`QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)`

Thanks guys.

**Comment by ZhouBin818** [comment]
hey bro,could you tell me how you solve this question which I have encounter？

**Comment by ManChrys** [comment]
Hello guys,

as i notice i have the above error when there are surfaces close to lidar, or when the indoor place is small. Even if this error exists, i can create pointcloud though.

**Comment by wuming122333** [comment]
> 我有同样的问题，你是怎么解决的？谢谢

您好，我也遇到了这个问题，您是怎么解决的？谢谢
