### ISSUE TITLE
有关重力对齐的问题

### ISSUE THREAD

**Issue by hr2894235132** [hku-mars/FAST_LIO#193]
您好！首先非常感谢您优秀的工作，我也进行了测试，效果很不错。
想请问一下您有像vins-mono里做过重力对齐相关的操作嘛？

**Comment by liang0724s** [comment]
> 您好！首先非常感谢您优秀的工作，我也进行了测试，效果很不错。 想请问一下您有像vins-mono里做过重力对齐相关的操作嘛？

参考下面这篇知乎文章可能找到你想要的答案
[一文详解三种重力优化方法](https://zhuanlan.zhihu.com/p/437872881)
