### ISSUE TITLE
关于数据的time字段

### ISSUE THREAD

**Issue by ZhangZh3ng** [hku-mars/FAST_LIO#196]
由于本人实际用过的激光雷达非常有限，有些问题想向大家请教：
1. 目前time字段的精度大致在一个什么样的水平，相较于使用x, y字段求反正切求得的时间，time字段在精度上具有优势吗（目前很多较新的算法都直接使用time字段，所以我猜这个时间精度应该挺高的，但还是想确认一下）
2. 为什么一帧点云中每个点的time可以都不相同？拿16线雷达举例，按说每隔16个点应该具有相同的时间戳，但我发现实际数据中通常不是这样，而是每个点都有自己特定的时间，为什么会这样，难道说所有线不是同步发射激光的吗

**Comment by XW-HKU** [comment]
1. 我倾向于使用time字段，因为
a. 小fov雷达无法通过反正切计算时间戳
b. 有些情况（比如对天空）下雷达会返回0.0.0点，无法计算时间戳

2. 不同雷达硬件方案不一样，同步发射激光不一定更有意义。

**Comment by ZhangZh3ng** [comment]
> 1. 我倾向于使用time字段，因为
>    a. 小fov雷达无法通过反正切计算时间戳
>    b. 有些情况（比如对天空）下雷达会返回0.0.0点，无法计算时间戳
> 2. 不同雷达硬件方案不一样，同步发射激光不一定更有意义。

感谢指点！
