### ISSUE TITLE
雷达time相关的问题

### ISSUE THREAD

**Issue by chenjianqiang199526** [hku-mars/FAST_LIO#199]
你好，我用的是镭神的16线雷达录制的雷达数据，我看了一下数据的格式跟velodyne的格式是一样的都是x y z instensity ring time ,因此我用velodyne.yaml的参数，但是为什么一直报的Failed to find match for field 'time'

**Comment by PigletPh** [comment]
@chenjianqiang199526 你好，这个问题解决了吗

**Comment by TangSZk** [comment]
更改ros包发布话题之前每个点的数据格式使用fastlio定义的格式（见preprocess.h中对应的格式）或在fastlio中增加你所用数据类型的数据结构

**Comment by shahaizi0** [comment]
更改ros包发布话题之前每个点的数据格式使用fastlio定义的格式（见preprocess.h中对应的格式）或在fastlio中增加你所用数据类型的数据结构

**Comment by PigletPh** [comment]
@TangSZk 你好，我对比了下FAST-LIO中velodyne雷达定义格式，发现是一样的，但我将time的类型从double转为float，编译没有错但是雷达数据无法导入到，请问怎么回事，万分感谢
![image](https://user-images.githubusercontent.com/44089510/228789583-9e80594f-cbf6-4421-833f-b252634c359f.png)

**Comment by shaoxh** [comment]
Make sure that field 'time' is really in your the ROS topic.
Got a similar here: https://github.com/hku-mars/FAST_LIO/issues/302

**Comment by lijing137** [comment]
> @TangSZk 你好，我对比了下FAST-LIO中velodyne雷达定义格式，发现是一样的，但我将time的类型从double转为float，编译没有错但是雷达数据无法导入到，请问怎么回事，万分感谢 ![image](https://user-images.githubusercontent.com/44089510/228789583-9e80594f-cbf6-4421-833f-b252634c359f.png)

You can try using the latest LiDAR driver（my lidar is leishenC32）, I solved the “Failed to find match for field time'' issue this way.

**Comment by 1BlackBaby** [comment]
@PigletPh 大佬您好，我用的也是镭神的c16型号的雷达，但我一直跑不起来，我可以问一下您的具体配置吗？或者具体改了哪些代码和配置
