### ISSUE TITLE
禾赛激光雷达适配

### ISSUE THREAD

**Issue by JiangxinkeTao** [hku-mars/FAST_LIO#201]
请问使用禾赛Panda人QT64激光雷达进行适配，配置参数文件该怎么写呢，使用Issues中（如#141）提到的一些方法进行修改，都没什么用，诚盼作者解答一下，感谢！ @XW-HKU

**Comment by lukechencqu** [comment]
同问

**Comment by 85256638** [comment]
@JiangxinkeTao 大佬，请问搞定了禾赛适配吗？

**Comment by JiangxinkeTao** [comment]
> [@JiangxinkeTao](https://github.com/JiangxinkeTao) 大佬，请问搞定了禾赛适配吗？

不好意思，我今天才看到消息，搞定了，但是时间太久了，我都忘记了怎么适配的。

**Comment by JiangxinkeTao** [comment]
> [@JiangxinkeTao](https://github.com/JiangxinkeTao) 大佬，请问搞定了禾赛适配吗？

我隐约记得好像是需要仿照他们写得其他雷达的一个结构体，仿写一个何塞的激光雷达适配结构体
