### ISSUE TITLE
avia采集的上下楼梯数据包解算效果

### ISSUE THREAD

**Issue by cherie6866** [hku-mars/FAST_LIO#203]
您好，这个算法在一些特定场合下采集的数据解算结果跟预想的不太一样，我这边用avia采集了一份雷达数据：过程是先从一个楼道走，然后从楼道尽头的步梯上去，紧接又从楼梯返回，再次扫描刚才的楼道，解算过程显示，后边再次扫描的同一楼道时，解算结果不重合了，能帮忙看一下是什么原因吗？

![Screenshot from 2022-12-06 17-38-53](https://user-images.githubusercontent.com/10471715/206067264-47f4ce93-c7e6-46fc-a352-703ba633c1c9.png)

数据包在这里：
链接：https://pan.baidu.com/s/16WDwJsIq-hzboVkLiO9PPg?pwd=hjkl 
提取码：hjkl

期待您的回复！

**Comment by Ackermann10** [comment]
你好，请问这个问题你解决了吗

**Comment by cherie6866** [comment]
> 你好，请问这个问题你解决了吗

没有解决
