### ISSUE TITLE
AVIA航插线

### ISSUE THREAD

**Issue by GavinGaoYan** [hku-mars/FAST_LIO#207]
AVIA原装航插线巨长，而且必须用它的转换小盒子？
请问你们是DIY了一条连接线吗？可不可以分享一下。

**Comment by GavinGaoYan** [comment]
.

**Comment by Tomato1107** [comment]
可以按引脚的线需定义说明拆分出来接网口，电源，同步信号，但需要注意接电源的电压。建议仔细阅读说明书。或者可以买一根https://store.dji.com/cn/product/livox-mid-360?vid=130851&set_region=CN&from=store-nav 这里面的 Livox 航插一分三线

**Comment by GavinGaoYan** [comment]
> 可以按引脚的线序定义说明拆分出来接网口，电源，同步信号，但需要注意接电源的电压。建议仔细阅读说明书。或者可以参考https://store.dji.com/cn/product/livox-mid-360?vid=130851&set_region=CN&from=store-nav 这里面的 Livox 航插一分三线，这根线能不能用还需要看mid360说明书里面的线序定义和其他激光雷达是不是一样的

多谢，我明白你的意思。你们的工作看起来就是用的这种方法？可以分享一下怎么实现的吗？
![image](https://user-images.githubusercontent.com/29242454/211985178-0331d47a-39cd-4557-9ac3-7f160a178c8d.png)

**Comment by Tomato1107** [comment]
我不是hku的，尴尬了

Squirtle ***@***.***>于2023年1月12日 周四14:34写道：
