### ISSUE TITLE
能否增加demo数据的百度网盘下载链接

### ISSUE THREAD

**Issue by jhx646018057** [hku-mars/FAST_LIO#21]
作者你好，能否增加demo数据的百度网盘下载链接，google的资源内地打开比较困难，谢谢。还有r2live的demo数据。

**Comment by kxch928925819** [comment]
不fanqiang，走到这一步，你的确很厉害！可以试试gitee，那上面的东西有一部分不需要fanqiang就可以下载！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hku-mars/FAST_LIO"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月22日(星期二) 上午9:41
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[hku-mars/FAST_LIO] 能否增加demo数据的百度网盘下载链接 (#21)





 
作者你好，能否增加demo数据的百度网盘下载链接，google的资源内地打开比较困难，谢谢。还有r2live的demo数据。

**Comment by jhx646018057** [comment]
我说的是作者的rosbag example下载链接。

**Comment by kxch928925819** [comment]
先转存自己的google云端硬盘，再下载试试！





------------------ 原始邮件 ------------------
发件人: jhx646018057 ***@***.***&gt;
发送时间: 2021年6月22日 17:34
收件人: hku-mars/FAST_LIO ***@***.***&gt;
抄送: Weiguo Zhao ***@***.***&gt;, Comment ***@***.***&gt;
主题: 回复：[hku-mars/FAST_LIO] 能否增加demo数据的百度网盘下载链接 (#21)





 
我说的是作者的rosbag example下载链接。

**Comment by XW-HKU** [comment]
好的，近期就会添加。
