### ISSUE TITLE
编译报错问题

### ISSUE THREAD

**Issue by Que121** [hku-mars/FAST_LIO#214]
您好，我进行编译时发生如下报错，环境为Ubuntu20.04，ros版本为noetic，pcl版本为-1.10
![2023-02-07_13-09](https://user-images.githubusercontent.com/97080652/217154706-2761a400-a536-45fa-9590-57ec790728fc.png)
![2023-02-07_13-09_1](https://user-images.githubusercontent.com/97080652/217154688-692170c4-5e4a-477e-ade0-d0c4fda56d3c.png)

**Comment by Que121** [comment]
收到了，谢谢！

**Comment by Que121** [comment]
收到了，谢谢！

**Comment by Que121** [comment]
收到了，谢谢！

**Comment by BlueAkoasm** [comment]
你好，请问最后是怎么解决的？

**Comment by Que121** [comment]
收到了，谢谢！
