### ISSUE TITLE
No velocity data in output odometry

### ISSUE THREAD

**Issue by Pallav1299** [hku-mars/FAST_LIO#215]
Hi. Thanks for sharing your work.

While testing FastLIO2 for autonomous navigation application, I realized that there is no velocity data(i.e. twist message with covariance is 0) in the output odometry.

Question:
- In real applications, where we need to fuse the external localization data(VIO, LIO) into Flight Controller(FCU) for autonomous navigation, is it actually a good practice to fuse only position estimate and no velocity estimate into the FCU?

**Comment by XW-HKU** [comment]
you could modify the code to contain velocity in ros topic.
