### ISSUE TITLE
精度评估

### ISSUE THREAD

**Issue by forcazzx** [hku-mars/FAST_LIO#217]
请问论文中的绝对平移误差rmse是怎么评估的呢？
我下载了源码之后运行了nclt数据集，并用evo_ape评估了绝对平移误差rmse值，发现普遍比论文中给出的误差小，例如nclt9(20130110)这组，论文中给出的误差在5m左右，但是本地跑出来的误差为0.99m。

**Comment by forcazzx** [comment]
这是运行的配置文件
![image](https://user-images.githubusercontent.com/39309752/222700313-db6bd47f-f7a5-4817-8a87-a5150d677368.png)

**Comment by duanxz0127** [comment]
> 请问论文中的绝对平移误差rmse是怎么评估的呢？ 我下载了源码之后运行了nclt数据集，并用evo_ape评估了绝对平移误差rmse值，发现普遍比论文中给出的误差小，例如nclt9(20130110)这组，论文中给出的误差在5m左右，但是本地跑出来的误差为0.99m。

请问你找到原因了吗？我计算出的nclt9(20130110)这组ATE也是0.9m

**Comment by hr2894235132** [comment]
> 这是运行的配置文件 ![image](https://user-images.githubusercontent.com/39309752/222700313-db6bd47f-f7a5-4817-8a87-a5150d677368.png)

您好，想问一下你NCLT的真值是怎么得到的呢？我下载的时间戳好像不对
