### ISSUE TITLE
Detection below 1m

### ISSUE THREAD

**Issue by aoki-y** [hku-mars/FAST_LIO#219]
FAST-Lio seems to delete point clouds less than 1m. 
I want it to be less than 0.8m instead of less than 1m, which parameter should I modify?

**Comment by PengKunPROO** [comment]
Maybe livox avia can not collect the points less than 1m from your position?

**Comment by bianhao3321** [comment]
set param "blind" at yaml file in  config

**Comment by aoki-y** [comment]
Thank you for answering.
I solved it by changing the setting of "bling"
