### ISSUE TITLE
slightly different results for multiple runs

### ISSUE THREAD

**Issue by wwtinwhu** [hku-mars/FAST_LIO#222]
Hello,

When test a bigger data (e.g. 900 meters in 10 min), the ATE calculated for multiple runs are slightly different. I noticed that in a small data, the result is more stable. It depends on the performance of the computer?

When quantitatively compare different lio algorithms, How do you make a fair comparison？Have you ever encountered this phenomenon during the test？

Regards,
Weitong Wu

**Comment by SabraHashemi** [comment]
@wwtinwhu  I have the same problem, did you solve it ? or any idea?

**Comment by Freeskylover** [comment]
> [@wwtinwhu](https://github.com/wwtinwhu) I have the same problem, did you solve it ? or any idea?

me too
