### ISSUE TITLE
How to use with Livox mid360

### ISSUE THREAD

**Issue by vanstrong12138** [hku-mars/FAST_LIO#224]
mid360 can only use Livox-SDK2 and livox_ros_driver2.

**Comment by XW-HKU** [comment]
just use it

**Comment by vanstrong12138** [comment]
> just use it

![image](https://user-images.githubusercontent.com/94519379/226244054-5787a1ed-c356-4ce9-a226-d8d3151dfee1.png)
![image](https://user-images.githubusercontent.com/94519379/226244083-7d9c98ea-3c31-45c8-9475-1051691302ed.png)
![image](https://user-images.githubusercontent.com/94519379/226245467-b0e5779f-72c8-4aa9-aacc-56ce185ef251.png)
![image](https://user-images.githubusercontent.com/94519379/226244093-bb3ba06f-963c-4c8b-ab88-7c552dddedd5.png)
my livox_ros_driver2 has already built in my '/home/d_livox/src/'  ,but in the'/home/fastlio2',  i do 'source ~/d_livox/devel/setup.bash'.  no error.  but when i 'catkin_make' . it is error

**Comment by geniusdo** [comment]
just put both livox_ros_driver and livox_ros_driver2 in your src folder
