### ISSUE TITLE
地图的保存

### ISSUE THREAD

**Issue by huduo0812** [hku-mars/FAST_LIO#23]
我用这个算法构建了一个非常满意的地方， 可是应该用什么方法保存下来用来定位导航呢？

**Comment by XW-HKU** [comment]
We will support saving PCD file soon.

**Comment by huduo0812** [comment]
> 我们将很快支持保存 PCD 文件。

好的，谢谢

**Comment by XW-HKU** [comment]
现在的算法可以支持保存每一帧点云（世界坐标系下）到pcd文件，可以参考readme去操作。

**Comment by huduo0812** [comment]
> 现在的算法可以支持保存每一帧点云（世界坐标系下）到pcd文件，可以参考readme去操作。
非常感谢你们的更新，还有问题需要请教一下，就是，怎么可以像https://github.com/Livox-SDK/livox_mapping这个算法一样一次保存整个地图在一个pcd文件里，然后再转为栅格地图用来定位和导航

**Comment by XW-HKU** [comment]
你需要保存哪种形式的地图呢，是所有帧的点云的累积稠密地图？，还是ICP所用到的稀疏点云地图？

**Comment by kxch928925819** [comment]
稠密点云，这样抽稀工作可以放在其他软件执行！
再者，有三个个疑问：闭环精度评定的参数能否调整，在程序里怎么调整！
第二，能否直接输出精度评定的数据，图表。
第三，能否通过采集设备静置，得到静置时间段的采集器位置坐标，（譬如程序设定，当imu移动在10秒钟不超过10cm，程序输出该点坐标信息），以便在点云平移旋转时方便处理！
哈哈😄！水平所限，如有冒犯，敬请谅解！ 我就是一个老测量员！




------------------ 原始邮件 ------------------
发件人: Cris.Wei ***@***.***&gt;
发送时间: 2021年7月6日 16:10
收件人: hku-mars/FAST_LIO ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: 回复：[hku-mars/FAST_LIO] 地图的保存 (#23)





 
你需要保存哪种形式的地图呢，是所有帧的点云的累积稠密地图？，还是ICP所用到的稀疏点云地图？

**Comment by huduo0812** [comment]
> 你需要保存哪种形式的地图呢，是所有帧的点云的累积稠密地图？，还是ICP所用到的稀疏点云地图？

是的，我想要那种所有帧的累积的地图，然后转成栅格地图，用来室外定位导航。每一帧的点云保存下来都只是局部的吧，我前几天试过修改laserMapping.cpp里的代码，成功保存了稠密的pcd点云地图，但是没有颜色，都是白色，然后想根据intensity渲染一下点云，但是发现intensity都是0，最后根据z轴渲染了一下，非常丑，hhhh

**Comment by EloyAldao** [comment]
This is from v1, but worked also on v2.
Add the ap.intensity = pl[j].intensity; and ap.intensity = pl[k].intensity; lines and recompile:

```
 if(j == uint(last_surface+point_filter_num-1))
  {
    PointType ap;
    ap.x = pl[j].x;
    ap.y = pl[j].y;
    ap.z = pl[j].z;
    ap.intensity = pl[j].intensity;
    ap.curvature = pl[j].curvature;
    pl_surf.push_back(ap);

    last_surface = -1;
  }
}
else
{
  if(types[j].ftype==Edge_Jump || types[j].ftype==Edge_Plane)
  {
    pl_corn.push_back(pl[j]);
  }
  if(last_surface != -1)
  {
    PointType ap;
    for(uint k=last_surface; k<j; k++)
    {
      ap.x += pl[k].x;
      ap.y += pl[k].y;
      ap.z += pl[k].z;
      ap.intensity = pl[k].intensity;
      ap.curvature += pl[k].curvature;
    }
    ap.x /= (j-last_surface);
    ap.y /= (j-last_surface);
    ap.z /= (j-last_surface);
    ap.curvature /= (j-last_surface);
    pl_surf.push_back(ap);
  }
  last_surface = -1;
```

**Comment by XW-HKU** [comment]
> > 你需要保存哪种形式的地图呢，是所有帧的点云的累积稠密地图？，还是ICP所用到的稀疏点云地图？
> 
> 是的，我想要那种所有帧的累积的地图，然后转成栅格地图，用来室外定位导航。每一帧的点云保存下来都只是局部的吧，我前几天试过修改laserMapping.cpp里的代码，成功保存了稠密的pcd点云地图，但是没有颜色，都是白色，然后想根据intensity渲染一下点云，但是发现intensity都是0，最后根据z轴渲染了一下，非常丑，hhhh

最新的代码已经改成了保存成一个累积的点云，现在rivz里面的当前帧点云上色使用的就是intensity，你可以看看保存出来的pcd file有没有intensity.

**Comment by XW-HKU** [comment]
> This is from v1, but worked also on v2.
> Add the ap.intensity = pl[j].intensity; and ap.intensity = pl[k].intensity; lines and recompile:
> 
> ```
>  if(j == uint(last_surface+point_filter_num-1))
>   {
>     PointType ap;
>     ap.x = pl[j].x;
>     ap.y = pl[j].y;
>     ap.z = pl[j].z;
>     ap.intensity = pl[j].intensity;
>     ap.curvature = pl[j].curvature;
>     pl_surf.push_back(ap);
> 
>     last_surface = -1;
>   }
> }
> else
> {
>   if(types[j].ftype==Edge_Jump || types[j].ftype==Edge_Plane)
>   {
>     pl_corn.push_back(pl[j]);
>   }
>   if(last_surface != -1)
>   {
>     PointType ap;
>     for(uint k=last_surface; k<j; k++)
>     {
>       ap.x += pl[k].x;
>       ap.y += pl[k].y;
>       ap.z += pl[k].z;
>       ap.intensity = pl[k].intensity;
>       ap.curvature += pl[k].curvature;
>     }
>     ap.x /= (j-last_surface);
>     ap.y /= (j-last_surface);
>     ap.z /= (j-last_surface);
>     ap.curvature /= (j-last_surface);
>     pl_surf.push_back(ap);
>   }
>   last_surface = -1;
> ```

Good Jobs, I will add these into codes. Thank you very much!

**Comment by XW-HKU** [comment]
> 稠密点云，这样抽稀工作可以放在其他软件执行！ 再者，有三个个疑问：闭环精度评定的参数能否调整，在程序里怎么调整！ 第二，能否直接输出精度评定的数据，图表。 第三，能否通过采集设备静置，得到静置时间段的采集器位置坐标，（譬如程序设定，当imu移动在10秒钟不超过10cm，程序输出该点坐标信息），以便在点云平移旋转时方便处理！ 哈哈smile！水平所限，如有冒犯，敬请谅解！ 我就是一个老测量员！
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Cris.Wei ***@***.***&gt; 发送时间: 2021年7月6日 16:10 收件人: hku-mars/FAST_LIO ***@***.***&gt; 抄送: Subscribed ***@***.***&gt; 主题: 回复：[hku-mars/FAST_LIO] 地图的保存 (#23) 你需要保存哪种形式的地图呢，是所有帧的点云的累积稠密地图？，还是ICP所用到的稀疏点云地图？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

实在不好意思，测绘的这些我不太懂，感觉应该可以在点云后处理里面实现？

**Comment by XW-HKU** [comment]
> > This is from v1, but worked also on v2.
> > Add the ap.intensity = pl[j].intensity; and ap.intensity = pl[k].intensity; lines and recompile:
> > ```
> >  if(j == uint(last_surface+point_filter_num-1))
> >   {
> >     PointType ap;
> >     ap.x = pl[j].x;
> >     ap.y = pl[j].y;
> >     ap.z = pl[j].z;
> >     ap.intensity = pl[j].intensity;
> >     ap.curvature = pl[j].curvature;
> >     pl_surf.push_back(ap);
> > 
> >     last_surface = -1;
> >   }
> > }
> > else
> > {
> >   if(types[j].ftype==Edge_Jump || types[j].ftype==Edge_Plane)
> >   {
> >     pl_corn.push_back(pl[j]);
> >   }
> >   if(last_surface != -1)
> >   {
> >     PointType ap;
> >     for(uint k=last_surface; k<j; k++)
> >     {
> >       ap.x += pl[k].x;
> >       ap.y += pl[k].y;
> >       ap.z += pl[k].z;
> >       ap.intensity = pl[k].intensity;
> >       ap.curvature += pl[k].curvature;
> >     }
> >     ap.x /= (j-last_surface);
> >     ap.y /= (j-last_surface);
> >     ap.z /= (j-last_surface);
> >     ap.curvature /= (j-last_surface);
> >     pl_surf.push_back(ap);
> >   }
> >   last_surface = -1;
> > ```
> 
> Good Jobs, I will add these into codes. Thank you very much!

Already merged in the codes.

**Comment by huduo0812** [comment]
> > > 你需要保存哪种形式的地图呢，是所有帧的点云的累积稠密地图？，还是ICP所用到的稀疏点云地图？
> > 
> > 
> > 是的，我想要那种所有帧的累积的地图，然后转成栅格地图，用来室外定位导航。每一帧的点云保存下来都只是局部的吧，我前几天试过修改laserMapping.cpp里的代码，成功保存了稠密的pcd点云地图，但是没有颜色，都是白色，然后想根据intensity渲染一下点云，但是发现intensity都是0，最后根据z轴渲染了一下，非常丑，hhhh
> 
> 最新的代码已经改成了保存成一个累积的点云，现在rivz里面的当前帧点云上色使用的就是intensity，你可以看看保存出来的pcd file有没有intensity.

好的，谢谢你们，我明天试试

**Comment by huduo0812** [comment]
> > > 你需要保存哪种形式的地图呢，是所有帧的点云的累积稠密地图？，还是ICP所用到的稀疏点云地图？
> > 
> > 
> > 是的，我想要那种所有帧的累积的地图，然后转成栅格地图，用来室外定位导航。每一帧的点云保存下来都只是局部的吧，我前几天试过修改laserMapping.cpp里的代码，成功保存了稠密的pcd点云地图，但是没有颜色，都是白色，然后想根据intensity渲染一下点云，但是发现intensity都是0，最后根据z轴渲染了一下，非常丑，hhhh
> 
> 最新的代码已经改成了保存成一个累积的点云，现在rivz里面的当前帧点云上色使用的就是intensity，你可以看看保存出来的pcd file有没有intensity.


![image](https://user-images.githubusercontent.com/81087363/124697141-e2126e80-df18-11eb-8290-c8ba667a5ba1.png)
已经保存成 累积的点云的，但是颜色和rviz里面看到的不太一样，

**Comment by XW-HKU** [comment]
> > > > 你需要保存哪种形式的地图呢，是所有帧的点云的累积稠密地图？，还是ICP所用到的稀疏点云地图？
> > > 
> > > 
> > > 是的，我想要那种所有帧的累积的地图，然后转成栅格地图，用来室外定位导航。每一帧的点云保存下来都只是局部的吧，我前几天试过修改laserMapping.cpp里的代码，成功保存了稠密的pcd点云地图，但是没有颜色，都是白色，然后想根据intensity渲染一下点云，但是发现intensity都是0，最后根据z轴渲染了一下，非常丑，hhhh
> > 
> > 
> > 最新的代码已经改成了保存成一个累积的点云，现在rivz里面的当前帧点云上色使用的就是intensity，你可以看看保存出来的pcd file有没有intensity.
> 
> ![image](https://user-images.githubusercontent.com/81087363/124697141-e2126e80-df18-11eb-8290-c8ba667a5ba1.png)
> 已经保存成 累积的点云的，但是颜色和rviz里面看到的不太一样，

change what to visualize/color by pressing 1,2,3,4,5.
1 is all random
2 is X values
3 is Y values
4 is Z values
5 is intensity

**Comment by huduo0812** [comment]
> > > > > 你需要保存哪种形式的地图呢，是所有帧的点云的累积稠密地图？，还是ICP所用到的稀疏点云地图？
> > > > 
> > > > 
> > > > 是的，我想要那种所有帧的累积的地图，然后转成栅格地图，用来室外定位导航。每一帧的点云保存下来都只是局部的吧，我前几天试过修改laserMapping.cpp里的代码，成功保存了稠密的pcd点云地图，但是没有颜色，都是白色，然后想根据intensity渲染一下点云，但是发现intensity都是0，最后根据z轴渲染了一下，非常丑，hhhh
> > > 
> > > 
> > > 最新的代码已经改成了保存成一个累积的点云，现在rivz里面的当前帧点云上色使用的就是intensity，你可以看看保存出来的pcd file有没有intensity.
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/81087363/124697141-e2126e80-df18-11eb-8290-c8ba667a5ba1.png)
> > 已经保存成 累积的点云的，但是颜色和rviz里面看到的不太一样，
> 
> change what to visualize/color by pressing 1,2,3,4,5.
> 1 is all random
> 2 is X values
> 3 is Y values
> 4 is Z values
> 5 is intensity

谢谢谢，现在效果非常好
![image](https://user-images.githubusercontent.com/81087363/124729765-506c2680-df43-11eb-9e54-7a1686e92e17.png)

**Comment by GRF-Sunomikp31** [comment]
@huduo0812 Hi，想咨询下你，如果利用保存的PCD点云文件重新定位呢？
