### ISSUE TITLE
find a bug in mtkmath.hpp 

### ISSUE THREAD

**Issue by biao-y** [hku-mars/FAST_LIO#235]
https://github.com/hku-mars/FAST_LIO/blob/02d022e3164cc39afdc56618a056bbaac9aa4d57/include/IKFoM_toolkit/mtk/src/mtkmath.hpp#L253
scalar mult = cos_sinc.second * scale;  // bug !!! 应该是scalar mult = cos_sinc.second / sqrt(norm2);

**Comment by Joanna-HE** [comment]
Hi, there is no bug. It is mult = cos_sinc.second * scale, sqrt(norm2) has already been divided in the cos_sinc_sqrt() function.

**Comment by Ecstasy-EC** [comment]
The issue is closed for being solved.
