### ISSUE TITLE
Z轴漂移问题

### ISSUE THREAD

**Issue by cbnann** [hku-mars/FAST_LIO#237]
你好，想问下我用固态激光m1测试城区开放道路，激光去畸变肉眼可见比较良好，但是在平地上pitch角却比较大，导致pose里面的Ｚ一直变大，点云图往上翘起，可能是什么原因呢，外参应该没有问题的。测试园区的时候也有飘逸，但是相对要好一些，室内场景飘移就很小。怎么解决这种问题呢

**Comment by billsonhohoho** [comment]
> 你好，想问下我用固态激光m1测试城区开放道路，激光去畸变肉眼可见比较良好，但是在平地上pitch角却比较大，导致pose里面的Ｚ一直变大，点云图往上翘起，可能是什么原因呢，外参应该没有问题的。测试园区的时候也有飘逸，但是相对要好一些，室内场景飘移就很小。怎么解决这种问题呢

请问解决了吗

**Comment by zjz0001** [comment]
请问是什么原因呢？我也是在室内定位效果良好，在树林里效果也不错，但是在大场景中就会有比较大的高度飘移，x和
y轴飘移倒挺小
