### ISSUE TITLE
没能复现 UAV_flip_over_0328-004.bag 在视频里的效果

### ISSUE THREAD

**Issue by hg-zt** [hku-mars/FAST_LIO#238]
https://www.youtube.com/watch?v=2OvjGnxszf8 3:59 对应的应该是这个 bag 吧？

反复测试最新的 commit [0dbfc6e](https://github.com/hku-mars/FAST_LIO/commit/0dbfc6e1cb0bd7fc209bee6de83c01b49ac9398a) ，翻转之后要么高度掉一截，地图也会变成两层；少数情况会直接发散。
到落地之后一段时间则必然发散。
![image](https://user-images.githubusercontent.com/44964100/231414669-9fe18650-4be2-40fa-ba10-798b188d3617.png)

测试命令
```
roslaunch fast_lio mapping_avia.launch
rosbag play UAV_flip_over_0328-004.bag
```

另外我也尝试了使用 use_sim_time 并开启 rosbag --clock，也没什么改善。

试其他 AVIA 下的 bag 时似乎是正常的。

**Comment by Ecstasy-EC** [comment]
回退到前一个commit能跑吗？

**Comment by hg-zt** [comment]
> 回退到前一个commit能跑吗？

也不行，回退到 02d022e3164cc39afdc56618a056bbaac9aa4d57 也是一样的效果，到 21 年 7 月（和视频时间最近）的 1087a72497d19c3ac19a608b89e28b5e62b00e2a 也差不多

换了一台机器也没什么改善

**Comment by Ecstasy-EC** [comment]
> > 回退到前一个commit能跑吗？
> 
> 也不行，回退到 [02d022e](https://github.com/hku-mars/FAST_LIO/commit/02d022e3164cc39afdc56618a056bbaac9aa4d57) 也是一样的效果，到 21 年 7 月（和视频时间最近）的 [1087a72](https://github.com/hku-mars/FAST_LIO/commit/1087a72497d19c3ac19a608b89e28b5e62b00e2a) 也差不多
> 
> 换了一台机器也没什么改善

稍后我们测一下看看，可能是参数的问题

**Comment by naisy** [comment]
I hit the same problem.
I changed the parameters and it seems to be better.

**FAST_LIO/launch/mapping_avia.launch**
**before:**
```
        <param name="feature_extract_enable" type="bool" value="0"/>
        <param name="point_filter_num" type="int" value="3"/>
        <param name="max_iteration" type="int" value="3" />
        <param name="filter_size_surf" type="double" value="0.5" />
        <param name="filter_size_map" type="double" value="0.5" />
        <param name="cube_side_length" type="double" value="1000" />
        <param name="runtime_pos_log_enable" type="bool" value="0" />
```
**after:**
```
        <param name="feature_extract_enable" type="bool" value="0"/>
        <param name="point_filter_num" type="int" value="1"/>
        <param name="max_iteration" type="int" value="3" />
        <param name="filter_size_surf" type="double" value="0.15" />
        <param name="filter_size_map" type="double" value="0.15" />
        <param name="cube_side_length" type="double" value="1000" />
        <param name="runtime_pos_log_enable" type="bool" value="0" />
```

**FAST_LIO/config/avia.yaml**
**before:**
```
    blind: 4
    path_en:  false
```
**after:**
```
    blind: 0.01
    path_en:  true
```
**Result:**
**angle1**
The drone flips and then drifts a bit.
![angle1](https://github.com/hku-mars/FAST_LIO/assets/8622180/8e450158-a1cf-4ad2-a464-b2b39fc37918)

**angle2**
From another angle, it looks good.
![angle2](https://github.com/hku-mars/FAST_LIO/assets/8622180/bee3935e-70ee-4751-83f9-9da8fbeae3a1)
