### ISSUE TITLE
Ask questions about the end-to-end error in the experimental part of your thesis

### ISSUE THREAD

**Issue by scyzero** [hku-mars/FAST_LIO#239]
Hello, thank you for your excellent work on the fastlio. I would like to ask, how do you locate and evaluate end-to-end error on the lili-om dataset. Because according to my experiment, the initial position and end position of the sensor group in the lili data set are not the same, so how can the error be accurately calculated.

**Comment by Ecstasy-EC** [comment]
Which sequence of the lili-om dataset did you use? We only use Schloss-1/2 and East for end-to-end error evaluation.
