### ISSUE TITLE
跑自己的数据出现问题

### ISSUE THREAD

**Issue by coder-lanni** [hku-mars/FAST_LIO#246]
![Screenshot from 2023-05-08 21-16-09](https://user-images.githubusercontent.com/55757088/236836360-616c8a8b-864e-4da0-96f1-9759e46727aa.png)
您好，我自己的雷达是速腾聚创的，通过转成velodyne后用fast-lio2跑总是一开始就出现上图这样的结果，然后就飘了，这是一个室内的小场景。我的雷达是z轴朝前走着扫描的（型号是rsbpearl），我有尝试将数据做一个旋转，但是还是会出现上图那样的结果。请问您知道这可能是什么问题吗。slam菜鸟一直搞不明白。

**Comment by snakehaihai** [comment]
跑的hilti挑战赛把。。这玩意要自己写个node 来重新publish他的时间戳
每个lidar最好都写个类似的转换 转到他已经有的几个lidar
![20230513_150523](https://github.com/hku-mars/FAST_LIO/assets/6070995/7e120cbc-7c95-4c35-8a4e-6409b747a8e2)
![20230513_150341](https://github.com/hku-mars/FAST_LIO/assets/6070995/57b965a4-91f4-4ad0-b35c-ed2fa4669f71)

**Comment by coder-lanni** [comment]
非常感谢您的回复！不过我跑的不是挑战赛的，只是自己的数据，后面我发现把launch文件的point_filter_num改为1就可以跑了

**Comment by snakehaihai** [comment]
你可以试试吧 挑战赛的BP的时间戳有问题。 我自己算的各点时间。 自己的BP 如果都调好的话 没问题
