### ISSUE TITLE
how to set mid_360 perfectly used in fast_lio? 

### ISSUE THREAD

**Issue by 95-peterchen** [hku-mars/FAST_LIO#249]
how to set mid_360 perfectly used in fast_lio? should it set the config similar to avia?

**Comment by Ecstasy-EC** [comment]
You can set up the config file similar to Avia.

**Comment by 885288421** [comment]
I have used mid-360 recored a rosbag for topic /livox/lidar and /livox/imu ,launch the mapping_avia.launch ,fast-lio doesn't work,no tf .
