### ISSUE TITLE
How to improve the pub frequency of odom? 

### ISSUE THREAD

**Issue by Joosoo1** [hku-mars/FAST_LIO#252]
Hello great author, the point cloud publish frequency of my lidar is 10hz, at this time the frequency of odom output from fast_lio is also 10hz, is there any way to increase the publish frequency of odom, I have some work that needs high frequency pose estimation.thanks！

**Comment by yijing2050** [comment]
I have come up with the same question. @Joosoo1 Have you solved it?

**Comment by Joosoo1** [comment]
I also have another laser slam algorithm: DLIO，you could try!,the odom freq is 100hz

**Comment by yijing2050** [comment]
Where can I find DLIO?&nbsp; in github?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年6月24日(星期六) 晚上9:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hku-mars/FAST_LIO] How to improve the pub frequency of odom?  (Issue #252)





 
I also have another laser slam algorithm: DLIO，you could try!,the odom freq is 100hz

**Comment by Joosoo1** [comment]
https://github.com/vectr-ucla/direct_lidar_inertial_odometry.git
Note its livox branch, as well as issues #4 and #5，Hope it will help you！
