### ISSUE TITLE
Questions about the IMU data of Livox Avia Rosbag

### ISSUE THREAD

**Issue by fanggenzaiXHBS** [hku-mars/FAST_LIO#253]
Hello, author, I am very sorry to bother you.
I downloaded the **Livox Avia Rosbag** you provided and found that the acceleration value of the IMU is basically close to 0 even when it is stationary, did you take gravity out of the IMU output。

**Comment by XW-HKU** [comment]
its unit is G（i.e. 9.8m/s2）

**Comment by Joosoo1** [comment]
> its unit is G（i.e. 9.8m/s2）

@XW-HKU    Can make the acceleration unit of imu output from livox in meters per second? If so, please let me know, thanks!

**Comment by daijicheng** [comment]
> > its unit is G（i.e. 9.8m/s2）
> 
> @XW-HKU Can make the acceleration unit of imu output from livox in meters per second? If so, please tell me, thanks!

I think the code in https://github.com/ziv-lin/livox_ros_driver_for_R2LIVE?tab=readme-ov-file will help you.
