### ISSUE TITLE
Velodyne point cloud visualization

### ISSUE THREAD

**Issue by jeho-lee** [hku-mars/FAST_LIO#256]
Hi. While I am trying to use FAST LIO from the ROS bag containing VLP-16 point clouds and IMU data, the odometry seems correct and consistent, but the point cloud is not shown in Rviz.

Below are the Rviz and velodyne.yaml configuration.

![image](https://github.com/hku-mars/FAST_LIO/assets/70247564/d98a4e50-7070-488d-a162-169cf8b5842c)

![image](https://github.com/hku-mars/FAST_LIO/assets/70247564/0fae443c-1aa8-45dc-ac12-1a93c22139f8)

I've tried to change some Rviz configurations (e.g., currPoints Topic to "/velodyne_points"), but didn't work.
Did I miss something to modify in load_livox.rviz configuration file? Any help would be thankful.

**Comment by lxystar00** [comment]
Hi, I have the same question, could i see your terminal? My terminal give me a warn 'No point, skip this scan!'. Thank you!!

**Comment by maffan-96** [comment]
> Hi, I have the same question, could i see your terminal? My terminal give me a warn 'No point, skip this scan!'. Thank you!!

Hey, were you able to resolve the issue?

**Comment by shaoxiang** [comment]
> > Hi, I have the same question, could i see your terminal? My terminal give me a warn 'No point, skip this scan!'. Thank you!!嗨，我有同样的问题，我能看到你的终端吗？我的终端给我一个警告“没有意义，跳过此扫描！谢谢！！
> 
> Hey, were you able to resolve the issue?嘿，你能解决这个问题吗？
Refer to #278 , please check the timestamps of IMU and Lidar

**Comment by yucong-zhang** [comment]
I'm having this problem with UrbanNav, any solutions?
