### ISSUE TITLE
mid70雷达和维特外置IMU的硬件时间戳同步如何操作，即激光和IMU的时间同步参数如何配置

### ISSUE THREAD

**Issue by 5204338** [hku-mars/FAST_LIO#260]
common:
    lid_topic:  "/livox/lidar"
    imu_topic:  "/wit/imu"
    time_sync_en: true         # ONLY turn on when external time synchronization is really not possible
    time_offset_lidar_to_imu: 1689742965.1697087288 
时间同步参数：time_offset_lidar_to_imu 的配置？
我现在设置该参数的方法是，每次激光雷达开启后，都配置一次，有什么一劳永逸，永久的配置该参数的方法吗？

**Comment by gc625-kodifly** [comment]
Hi, based on your imu topic, are you using the 10 axis imu from yahboom? if so, do you have any suggestions on the parameter values for acc_cov, gyr_cov, b_acc_cov, b_gyr_cov?

**Comment by WN-Wolf** [comment]
@5204338 你好，我也使用的是mid-70外加wit IMU，我通过LiDAR_IMU_Init得到一个txt文档
![image](https://github.com/user-attachments/assets/06bd634b-03a2-4566-88ef-808755da5784)
但是，我如何将txt中文档的内容对应t填写在config/avia.yaml文件中呢？
![image](https://github.com/user-attachments/assets/d31a54d5-27ae-435e-a6a3-bb8e7d3dc586)
