### ISSUE TITLE
使用avia测试最新代码，里程计错乱

### ISSUE THREAD

**Issue by ysingfun** [hku-mars/FAST_LIO#277]
**在Windows10上安装virtualbox虚拟机，运行Linux版本Ubuntu 20.04 
雷达 livox avia
房间环境
代码版本如下**
```
    commit 478d436813b966df94fb91dd759f477f1a246296 (HEAD -> main, origin/main, origin/HEAD)
    Author: zfc-zfc <625257073@qq.com>
    Date:   Fri Aug 18 16:23:52 2023 +0800
    
        Add launch file for mid360.
```

**程序开始运行前后始终保持静止，里程计在开始阶段短短几秒钟，就飘出了几十米的距离，请问这是什么原因导致的？感谢你的解答！**
![image](https://github.com/hku-mars/FAST_LIO/assets/37376098/fa5602ef-a759-4782-8cf5-6e4411de79d5)

**Comment by CanC-cern** [comment]
我也遇到了一样的问题，请问这个问题解决了吗
