### ISSUE TITLE
如何输出轨迹文件，类似TUM那种格式的TXT文件

### ISSUE THREAD

**Issue by wangchuanhao1231** [hku-mars/FAST_LIO#279]
slam小白，想利用EVO工具，不知道怎么修改代码才能得到EVO支持的格式，最好请大佬们回答的详细一点

**Comment by Breaking-Bugs** [comment]
I know it's a bit late, but better late than never. Here are the steps to convert `pos_log.txt` from FAST-LIO into TUM trajectory format:

## 1. Enable logging in your launch file

Go to your launch file and find this line:
```xml
<param name="path_save_en" type="bool" value="0" />
```

Change the `0` to `1` to make sure `pos_log.txt` will be saved (it will appear under the `Log/` directory of the FAST-LIO workspace).

## 2. Find the rosbag start time

Run:
```bash
rosbag info your_bag_file.bag
```

Note the start time, which is the base UNIX timestamp you will need. FAST-LIO stores only relative time in `pos_log.txt`.

## 3. Convert the log to TUM format

Save the following script as `convert_poslog_to_tum.py`:

```python
import argparse
from scipy.spatial.transform import Rotation as R

def convert_pos_log_to_tum(input_file, output_file, base_time):
    with open(input_file, 'r') as fin, open(output_file, 'w') as fout:
        for line in fin:
            tokens = line.strip().split()
            if len(tokens) < 7:
                continue
                
            relative_time = float(tokens[0])
            timestamp = base_time + relative_time
            
            roll, pitch, yaw = map(float, tokens[1:4])
            tx, ty, tz = map(float, tokens[4:7])
            
            quat = R.from_euler('xyz', [roll, pitch, yaw]).as_quat()  # x, y, z, w
            qx, qy, qz, qw = quat
            
            fout.write(f"{timestamp:.6f} {tx:.6f} {ty:.6f} {tz:.6f} "
                       f"{qx:.6f} {qy:.6f} {qz:.6f} {qw:.6f}\n")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Convert FAST-LIO pos_log.txt to TUM trajectory format")
    parser.add_argument("input", help="Path to input pos_log.txt")
    parser.add_argument("output", help="Path to output trajectory_tum.txt")
    parser.add_argument("--base_time", type=float, default=1627729762.57,
                        help="Base UNIX time to add to relative timestamps (default: 1627729762.57)")
    
    args = parser.parse_args()
    convert_pos_log_to_tum(args.input, args.output, args.base_time)
```

## 4. Usage example

With default base time:
```bash
python3 convert_poslog_to_tum.py pos_log.txt trajectory_tum.txt
```

With custom base time:
```bash
python3 convert_poslog_to_tum.py pos_log.txt trajectory_tum.txt --base_time 1650000000.0
```

You can now evaluate using `evo_ape`, for example:
```bash
evo_ape tum groundtruth.txt trajectory_tum.txt
```

Let me know if anything is unclear.

**Comment by wangchuanhao1231** [comment]
> I know it's a bit late, but better late than never. Here are the steps to convert `pos_log.txt` from FAST-LIO into TUM trajectory format:
> 
> ## 1. Enable logging in your launch file
> Go to your launch file and find this line:
> 
> <param name="path_save_en" type="bool" value="0" />
> Change the `0` to `1` to make sure `pos_log.txt` will be saved (it will appear under the `Log/` directory of the FAST-LIO workspace).
> 
> ## 2. Find the rosbag start time
> Run:
> 
> rosbag info your_bag_file.bag
> Note the start time, which is the base UNIX timestamp you will need. FAST-LIO stores only relative time in `pos_log.txt`.
> 
> ## 3. Convert the log to TUM format
> Save the following script as `convert_poslog_to_tum.py`:
> 
> import argparse
> from scipy.spatial.transform import Rotation as R
> 
> def convert_pos_log_to_tum(input_file, output_file, base_time):
>     with open(input_file, 'r') as fin, open(output_file, 'w') as fout:
>         for line in fin:
>             tokens = line.strip().split()
>             if len(tokens) < 7:
>                 continue
>                 
>             relative_time = float(tokens[0])
>             timestamp = base_time + relative_time
>             
>             roll, pitch, yaw = map(float, tokens[1:4])
>             tx, ty, tz = map(float, tokens[4:7])
>             
>             quat = R.from_euler('xyz', [roll, pitch, yaw]).as_quat()  # x, y, z, w
>             qx, qy, qz, qw = quat
>             
>             fout.write(f"{timestamp:.6f} {tx:.6f} {ty:.6f} {tz:.6f} "
>                        f"{qx:.6f} {qy:.6f} {qz:.6f} {qw:.6f}\n")
> 
> if __name__ == "__main__":
>     parser = argparse.ArgumentParser(description="Convert FAST-LIO pos_log.txt to TUM trajectory format")
>     parser.add_argument("input", help="Path to input pos_log.txt")
>     parser.add_argument("output", help="Path to output trajectory_tum.txt")
>     parser.add_argument("--base_time", type=float, default=1627729762.57,
>                         help="Base UNIX time to add to relative timestamps (default: 1627729762.57)")
>     
>     args = parser.parse_args()
>     convert_pos_log_to_tum(args.input, args.output, args.base_time)
> ## 4. Usage example
> With default base time:
> 
> python3 convert_poslog_to_tum.py pos_log.txt trajectory_tum.txt
> With custom base time:
> 
> python3 convert_poslog_to_tum.py pos_log.txt trajectory_tum.txt --base_time 1650000000.0
> You can now evaluate using `evo_ape`, for example:
> 
> evo_ape tum groundtruth.txt trajectory_tum.txt
> Let me know if anything is unclear.

Thank you for your patient reply. I have already solved the problem before, but I still want to thank you again
