### ISSUE TITLE
Odometry drift far after localization code running a period of time

### ISSUE THREAD

**Issue by wyb17js** [hku-mars/FAST_LIO#281]
Hi,
we are using ros2 to realize the automatic navigation function of the car, but the following problems appear in the positioning process:

There was no problem at the beginning of the program, the car gained its initial positioning and did not lose position in the process of moving. But after about 20 minutes of running, the car could not get its current position on the map, drifted far away, and the odometer increased and increased very fast.

The dark part is the local map, the light part is the global map, and the green part is the car body，The initial positioning state is as follows:
![22411483986_121331473861_P30926-115018_ B@f5d2164](https://github.com/hku-mars/FAST_LIO/assets/148990128/74f61218-7abd-4a17-8cd9-3310e56ad94f)
The lost position is such that the car has flown out of view and console prompts no effective point:
![169700925091022411483986_117515286358_5D201C93-2AE0-4fc5-883D-8C48A4CAC9CA](https://github.com/hku-mars/FAST_LIO/assets/148990128/32eb8c5e-6914-4627-b49b-a2b958294540)

We wanted to know why this happened, it is so suddenly and without warning.

Thank you!

**Comment by wyb17js** [comment]
It's worth mentioning that when I increased the scanning frequency of the radar, the positioning duration was extended.
The radar we use is mid360.

**Comment by ryanpdoc57** [comment]
@wyb17js are you using humble or foxy?

**Comment by wyb17js** [comment]
> @wyb17js are you using humble or foxy?

humble,do you have an opinion?

**Comment by xiaopengpeng** [comment]
> It's worth mentioning that when I increased the scanning frequency of the radar, the positioning duration was extended. The radar we use is mid360.

are you resolve this problem?
