### ISSUE TITLE
请问在生成点到平面距离的过程中生成的中间变量“s”是什么

### ISSUE THREAD

**Issue by ZhangZh3ng** [hku-mars/FAST_LIO#288]
在构建kf观测时有一个关于变量s的判断部分，正如如下代码中所示。看起来s的作用像是在检验这一组点到平面距离约束的有效性，把有关s的判断注释掉后里程计直接就飘了，可以看出这个判断非常关键。但在下始终无法理解这个变量的含义是什么，还有这个0.9又是怎么冒出来的？还望知道的大佬能解释一下，不胜感谢！
  ```
  if (esti_plane(pabcd, points_near, 0.1f))
        {
            float pd2 = pabcd(0) * point_world.x + pabcd(1) * point_world.y + pabcd(2) * point_world.z + pabcd(3);
            //  请问这个s是做什么用的，为什么这么算，它有什么物理意义吗 
            float s = 1 - 0.9 * fabs(pd2) / sqrt(p_body.norm()); 

            if (s > 0.9)
            {
                point_selected_surf[i] = true;
                normvec->points[i].x = pabcd(0); 
                normvec->points[i].y = pabcd(1);
                normvec->points[i].z = pabcd(2);
                normvec->points[i].intensity = pd2;
                res_last[i] = abs(pd2);
            }
        }
```

**Comment by TheSeanParker** [comment]
> 在构建kf观测时有一个关于变量s的判断部分，正如如下代码中所示。看起来s的作用像是在检验这一组点到平面距离约束的有效性，把有关s的判断注释掉后里程计直接就飘了，可以看出这个判断非常关键。但在下始终无法理解这个变量的含义是什么，还有这个0.9又是怎么冒出来的？还望知道的大佬能解释一下，不胜感谢！
> 
> ```
> if (esti_plane(pabcd, points_near, 0.1f))
>       {
>           float pd2 = pabcd(0) * point_world.x + pabcd(1) * point_world.y + pabcd(2) * point_world.z + pabcd(3);
>           //  请问这个s是做什么用的，为什么这么算，它有什么物理意义吗 
>           float s = 1 - 0.9 * fabs(pd2) / sqrt(p_body.norm()); 
> 
>           if (s > 0.9)
>           {
>               point_selected_surf[i] = true;
>               normvec->points[i].x = pabcd(0); 
>               normvec->points[i].y = pabcd(1);
>               normvec->points[i].z = pabcd(2);
>               normvec->points[i].intensity = pd2;
>               res_last[i] = abs(pd2);
>           }
>       }
> ```
I write a article for you
https://zhuanlan.zhihu.com/p/9429660492

**Comment by ZhangZh3ng** [comment]
> > 在构建kf观测时有一个关于变量s的判断部分，正如如下代码中所示。看起来s的作用像是在检验这一组点到平面距离约束的有效性，把有关s的判断注释掉后里程计直接就飘了，可以看出这个判断非常关键。但在下始终无法理解这个变量的含义是什么，还有这个0.9又是怎么冒出来的？还望知道的大佬能解释一下，不胜感谢！
> > ```
> > if (esti_plane(pabcd, points_near, 0.1f))
> >       {
> >           float pd2 = pabcd(0) * point_world.x + pabcd(1) * point_world.y + pabcd(2) * point_world.z + pabcd(3);
> >           //  请问这个s是做什么用的，为什么这么算，它有什么物理意义吗 
> >           float s = 1 - 0.9 * fabs(pd2) / sqrt(p_body.norm()); 
> > 
> >           if (s > 0.9)
> >           {
> >               point_selected_surf[i] = true;
> >               normvec->points[i].x = pabcd(0); 
> >               normvec->points[i].y = pabcd(1);
> >               normvec->points[i].z = pabcd(2);
> >               normvec->points[i].intensity = pd2;
> >               res_last[i] = abs(pd2);
> >           }
> >       }
> > ```
> 
> I write a article for you https://zhuanlan.zhihu.com/p/9429660492

Thanks a lot, your article is very helpful.
