### ISSUE TITLE
Indoor odometers are not very accurate

### ISSUE THREAD

**Issue by yangisod** [hku-mars/FAST_LIO#291]
Indoor odometers are not very accurate.
Inside I rotated the lidar around and the walls had a very obvious multiple layers
At the same time, the terminal keeps reporting error voxel leaf size. I tried to increase filter size surf, but no error was reported until 0.4
What parameters should I debug for this kind of problem

![2023-12-28_16-22](https://github.com/hku-mars/FAST_LIO/assets/44219258/51fcf8ba-babf-476d-8666-ecde4df24601)
![2023-12-28_11-07](https://github.com/hku-mars/FAST_LIO/assets/44219258/af96d0d8-381d-49a8-8072-bbef841446de)

**Comment by yangisod** [comment]
![2023-12-28_16-35](https://github.com/hku-mars/FAST_LIO/assets/44219258/933dbe0f-9e61-4d0d-b3ad-596eb3ef9efd)
I ran the scan again and the walls were still quickly stratified, what should I do

**Comment by dom-lee** [comment]
It would help if you tried to decrease `blind` parameter
