### ISSUE TITLE
Segmentation fault in ikd-tree rebuild process, cause by "Add_by_points". 

### ISSUE THREAD

**Issue by OliverShaoPT** [hku-mars/FAST_LIO#296]
I got a rare crush in ikd-tree, any idea?
![image](https://github.com/hku-mars/FAST_LIO/assets/37506826/9f147b5b-5435-4162-95e2-361ae921430c)
![image](https://github.com/hku-mars/FAST_LIO/assets/37506826/57f5205e-0f8c-4478-8d1d-89723e6dc186)

**Comment by JzHuai0108** [comment]
It seems I am having a similar problem on Ubuntu 22.
The segmentation fault occurs in the map_incremental() function.
