### ISSUE TITLE
建图到一半，直接停止增量建图，前面的部分也开始逐个消失

### ISSUE THREAD

**Issue by niuwenju** [hku-mars/FAST_LIO#297]
如下图所示，建图到一半，直接停止增量建图，前面的部分也开始逐个消失，有遇到过吗？
![Screenshot from 2024-01-15 12-41-44](https://github.com/hku-mars/FAST_LIO/assets/37408618/baeca068-aeaf-4208-a920-607ae791dd95)

**Comment by LiuYMUNI** [comment]
rviz可视化衰减时间的问题
