### ISSUE TITLE
Does Current Version support the VLP16?

### ISSUE THREAD

**Issue by wwtinwhu** [hku-mars/FAST_LIO#3]
Thanks for your excellent work! I notice that in the feature_extract.cpp, there is a lidar type selection among vlp16, horizon... So for the current version, can we run the vlp-16 + imu dataset with adjusting some parameters?

**Comment by XW-HKU** [comment]
Current FAST-LIO doesn't support VLP serials LiDAR. We may support them in the future.

**Comment by wwtinwhu** [comment]
> Current FAST-LIO doesn't support VLP serials LiDAR. We may support them in the future.

ok,thanks.

**Comment by yvzksgl** [comment]
Hello, I want to ask you to does the package support vlp16 now? Live point cloud data seems distorted and package does not produce map properly.
