### ISSUE TITLE
里程计信息，

### ISSUE THREAD

**Issue by huduo0812** [hku-mars/FAST_LIO#30]
启动了mapping_avia.launch会发布里程计信息，我现在正在给机器狗做定位导航，机器狗没有编码器，所以需要利用雷达和imu得出里程计信息，请问有什么方法可以只发布里程计信息吗

**Comment by XW-HKU** [comment]
the rostopic   /aft_mapped_to_init   is the odometry output

**Comment by huduo0812** [comment]
> the rostopic /aft_mapped_to_init is the odometry output

有只发布里程计信息的功能包吗，mapping_avia.launch这个运行起来太占资源

**Comment by XW-HKU** [comment]
太占资源是因为开着rviz显示点云吧，你可以关掉rviz里面的 点云显示 或者直接关掉rviz。点云发布并不占资源，显示点云更加吃资源。

**Comment by huduo0812** [comment]
> 太占资源是因为开着rviz显示点云吧，你可以关掉rviz里面的 点云显示 或者直接关掉rviz。点云发布并不占资源，显示点云非常占资源。

好的，我试试

**Comment by XW-HKU** [comment]
> > 太占资源是因为开着rviz显示点云吧，你可以关掉rviz里面的 点云显示 或者直接关掉rviz。点云发布并不占资源，显示点云非常占资源。
> 
> 好的，我试试

试完请告诉我有没有变化。

**Comment by huduo0812** [comment]
> > > 太占资源是因为开着rviz显示点云吧，你可以关掉rviz里面的 点云显示 或者直接关掉rviz。点云发布并不占资源，显示点云非常占资源。
> > 
> > 
> > 好的，我试试
> 
> 试完请告诉我有没有变化。

我把rviz那个参数设置成false，运行起来好一些，但是资源占用还是比较多的，而且还在一直发布点云和地图话题，这是不需要的话题
![image](https://user-images.githubusercontent.com/81087363/124893466-562e3e80-e00d-11eb-8f49-57893a284f4a.png)
现在只运行了livox_lidar_msg.launch  和  mapping_avia.launch  你们可以出一个功能包把雷达和imu发布里程计信息这个功能独立出来，很多项目是没有编码器的，无法提供导航包的里程计信息，非常感谢你的帮助！！

**Comment by XW-HKU** [comment]
> > > > 太占资源是因为开着rviz显示点云吧，你可以关掉rviz里面的 点云显示 或者直接关掉rviz。点云发布并不占资源，显示点云非常占资源。
> > > 
> > > 
> > > 好的，我试试
> > 
> > 
> > 试完请告诉我有没有变化。
> 
> 我把rviz那个参数设置成false，运行起来好一些，但是资源占用还是比较多的，而且还在一直发布点云和地图话题，这是不需要的话题
> ![image](https://user-images.githubusercontent.com/81087363/124893466-562e3e80-e00d-11eb-8f49-57893a284f4a.png)
> 现在只运行了livox_lidar_msg.launch 和 mapping_avia.launch 你们可以出一个功能包把雷达和imu发布里程计信息这个功能独立出来，很多项目是没有编码器的，无法提供导航包的里程计信息，非常感谢你的帮助！！

谢谢你的建议，我已经在launch file里面加了一个scan_publish_enable的开关，设置为0就会关掉点云publish。

但是有点奇怪，FASTLIO2理论上跑在ARM上的时候最多只会占用3个线程。你这个截图里面6个线程都这么高占用率着实不太对劲。

**Comment by huduo0812** [comment]
> > > > > 太占资源是因为开着rviz显示点云吧，你可以关掉rviz里面的 点云显示 或者直接关掉rviz。点云发布并不占资源，显示点云非常占资源。
> > > > 
> > > > 
> > > > 好的，我试试
> > > 
> > > 
> > > 试完请告诉我有没有变化。
> > 
> > 
> > 我把rviz那个参数设置成false，运行起来好一些，但是资源占用还是比较多的，而且还在一直发布点云和地图话题，这是不需要的话题
> > ![image](https://user-images.githubusercontent.com/81087363/124893466-562e3e80-e00d-11eb-8f49-57893a284f4a.png)
> > 现在只运行了livox_lidar_msg.launch 和 mapping_avia.launch 你们可以出一个功能包把雷达和imu发布里程计信息这个功能独立出来，很多项目是没有编码器的，无法提供导航包的里程计信息，非常感谢你的帮助！！
> 
> 谢谢你的建议，我已经在launch file里面加了一个scan_publish_enable的开关，设置为0就会关掉点云publish。
> 
> 但是有点奇怪，FASTLIO2理论上跑在ARM上的时候最多只会占用3个线程。你这个截图里面6个线程都这么高占用率着实不太对劲。

可能是livox_lidar_msg.launch也占用了，我现在下载一下你们新的代码试试

**Comment by XW-HKU** [comment]
> > > > > > 太占资源是因为开着rviz显示点云吧，你可以关掉rviz里面的 点云显示 或者直接关掉rviz。点云发布并不占资源，显示点云非常占资源。
> > > > > 
> > > > > 
> > > > > 好的，我试试
> > > > 
> > > > 
> > > > 试完请告诉我有没有变化。
> > > 
> > > 
> > > 我把rviz那个参数设置成false，运行起来好一些，但是资源占用还是比较多的，而且还在一直发布点云和地图话题，这是不需要的话题
> > > ![image](https://user-images.githubusercontent.com/81087363/124893466-562e3e80-e00d-11eb-8f49-57893a284f4a.png)
> > > 现在只运行了livox_lidar_msg.launch 和 mapping_avia.launch 你们可以出一个功能包把雷达和imu发布里程计信息这个功能独立出来，很多项目是没有编码器的，无法提供导航包的里程计信息，非常感谢你的帮助！！
> > 
> > 
> > 谢谢你的建议，我已经在launch file里面加了一个scan_publish_enable的开关，设置为0就会关掉点云publish。
> > 但是有点奇怪，FASTLIO2理论上跑在ARM上的时候最多只会占用3个线程。你这个截图里面6个线程都这么高占用率着实不太对劲。
> 
> 可能是livox_lidar_msg.launch也占用了，我现在下载一下你们新的代码试试

ARM上面CPU占用率过高的问题现在还有吗？

**Comment by huduo0812** [comment]
> > > > > > > 太占资源是因为开着rviz显示点云吧，你可以关掉rviz里面的 点云显示 或者直接关掉rviz。点云发布并不占资源，显示点云非常占资源。
> > > > > > 
> > > > > > 
> > > > > > 好的，我试试
> > > > > 
> > > > > 
> > > > > 试完请告诉我有没有变化。
> > > > 
> > > > 
> > > > 我把rviz那个参数设置成false，运行起来好一些，但是资源占用还是比较多的，而且还在一直发布点云和地图话题，这是不需要的话题
> > > > ![image](https://user-images.githubusercontent.com/81087363/124893466-562e3e80-e00d-11eb-8f49-57893a284f4a.png)
> > > > 现在只运行了livox_lidar_msg.launch 和 mapping_avia.launch 你们可以出一个功能包把雷达和imu发布里程计信息这个功能独立出来，很多项目是没有编码器的，无法提供导航包的里程计信息，非常感谢你的帮助！！
> > > 
> > > 
> > > 谢谢你的建议，我已经在launch file里面加了一个scan_publish_enable的开关，设置为0就会关掉点云publish。
> > > 但是有点奇怪，FASTLIO2理论上跑在ARM上的时候最多只会占用3个线程。你这个截图里面6个线程都这么高占用率着实不太对劲。
> > 
> > 
> > 可能是livox_lidar_msg.launch也占用了，我现在下载一下你们新的代码试试
> 
> ARM上面CPU占用率过高的问题现在还有吗？

![image](https://user-images.githubusercontent.com/81087363/125081441-974f4d00-e0f8-11eb-9793-6d2c3900ca00.png)

我把rviz和dense_publish_enable和scan_publish_enable都设置成0了，这样就只发布了里程计信息，cpu占用率没那么高了

**Comment by XW-HKU** [comment]
> > > > > > > > 太占资源是因为开着rviz显示点云吧，你可以关掉rviz里面的 点云显示 或者直接关掉rviz。点云发布并不占资源，显示点云非常占资源。
> > > > > > > 
> > > > > > > 
> > > > > > > 好的，我试试
> > > > > > 
> > > > > > 
> > > > > > 试完请告诉我有没有变化。
> > > > > 
> > > > > 
> > > > > 我把rviz那个参数设置成false，运行起来好一些，但是资源占用还是比较多的，而且还在一直发布点云和地图话题，这是不需要的话题
> > > > > ![image](https://user-images.githubusercontent.com/81087363/124893466-562e3e80-e00d-11eb-8f49-57893a284f4a.png)
> > > > > 现在只运行了livox_lidar_msg.launch 和 mapping_avia.launch 你们可以出一个功能包把雷达和imu发布里程计信息这个功能独立出来，很多项目是没有编码器的，无法提供导航包的里程计信息，非常感谢你的帮助！！
> > > > 
> > > > 
> > > > 谢谢你的建议，我已经在launch file里面加了一个scan_publish_enable的开关，设置为0就会关掉点云publish。
> > > > 但是有点奇怪，FASTLIO2理论上跑在ARM上的时候最多只会占用3个线程。你这个截图里面6个线程都这么高占用率着实不太对劲。
> > > 
> > > 
> > > 可能是livox_lidar_msg.launch也占用了，我现在下载一下你们新的代码试试
> > 
> > 
> > ARM上面CPU占用率过高的问题现在还有吗？
> 
> ![image](https://user-images.githubusercontent.com/81087363/125081441-974f4d00-e0f8-11eb-9793-6d2c3900ca00.png)
> 
> 我把rviz和dense_publish_enable和scan_publish_enable都设置成0了，这样就只发布了里程计信息，cpu占用率没那么高了

可否帮忙测试下，没有livox_lidar_msg.launch，也就是只播放bag的时候，cpu占用情况是怎样的？

**Comment by huduo0812** [comment]
![image](https://user-images.githubusercontent.com/81087363/125180836-69215880-e231-11eb-95d0-690b74764f99.png)
这是我什么都没运行的时候 cpu占用率从十几到二十几一直跳，
![image](https://user-images.githubusercontent.com/81087363/125180856-ae458a80-e231-11eb-9243-792674ec1ca3.png)
![image](https://user-images.githubusercontent.com/81087363/125180868-c3221e00-e231-11eb-95bf-6f2d4822c8b7.png)

这是运行bag的时候，占有率是30-60跳

**Comment by XW-HKU** [comment]
> ![image](https://user-images.githubusercontent.com/81087363/125180836-69215880-e231-11eb-95d0-690b74764f99.png)
> 这是我什么都没运行的时候 cpu占用率从十几到二十几一直跳，
> ![image](https://user-images.githubusercontent.com/81087363/125180856-ae458a80-e231-11eb-9243-792674ec1ca3.png)
> ![image](https://user-images.githubusercontent.com/81087363/125180868-c3221e00-e231-11eb-95bf-6f2d4822c8b7.png)
> 
> 这是运行bag的时候，占有率是30-60跳

ok
