### ISSUE TITLE
Gmapping navigation

### ISSUE THREAD

**Issue by fightforge** [hku-mars/FAST_LIO#308]
Hi,

I'm trying to generate a map using slam_gmapping, but I cannot get it to work. I'm a newbie in ROS, and I'm unsure if I'm using the best approach with gmapping to achieve 2D point-and-click navigation on RViz.

I'm using a Livox Mid-360 LiDAR on a 4WD direct-drive rover controlled by a Roboclaw controller without encoders. I'm using FAST_LIO to obtain odometry and pointcloud_to_laserscan to convert point cloud data to 2D laser scan. However, I'm encountering difficulties getting slam_gmapping to function.

Could you please suggest an alternative method to achieve 2D point-and-click navigation using your code?

Thank you.

**Comment by proxi666** [comment]
Hey I am also working with Livox MID-360, to make an large scale AMR..
I have successfully created a map using this algorithm, do you want to collaborate and work together in the project?

**Comment by ubicray** [comment]
Any chance you guys wanna share your config files for mid360? Don't see one anywhere around here

**Comment by fightforge** [comment]
Cannot collaborate, I'm not a developer.  For this issue, I'm trying point_lio, it seems to work better

**Comment by bcodesnow** [comment]
@fightforge You seemed to have success with pointcloud_to_laserscan and the livox mid 360. I am facing issues with it.
ROS (1) Noetic - did you use ROS2? 
https://github.com/ros-perception/pointcloud_to_laserscan/issues/91

The same install is working without issues with a realsense rgbd camera. 
Any idea is welcome! Thank you in advance.
