### ISSUE TITLE
话题/Laser_map为空

### ISSUE THREAD

**Issue by nowPB** [hku-mars/FAST_LIO#315]
你好，我在rviz中查看/Laser_map话题是空的，这个话题是对应的3d点云地图吗

**Comment by bird-sheep** [comment]
我也遇到了这个问题，里程计位姿计算应该是对的，但没有点云。请问你解决了吗？

**Comment by bird-sheep** [comment]
在yaml文件的publish里加上map_en: true
publish:
            path_en:  false
            map_en: true

**Comment by cuboya** [comment]
> 在yaml文件的publish里加上map_en: true publish: 出版： path_en: false path_en：false map_en: true map_en：true

您好，请问这个yml文件是哪个呢

**Comment by bird-sheep** [comment]
> > 在yaml文件的publish里加上map_en: true publish: 出版： path_en: false path_en：false map_en: true map_en：true
> 
> 您好，请问这个yml文件是哪个呢

在config文件夹里，你用哪种雷达，就在哪个里面加

**Comment by cuboya** [comment]
> > > 在yaml文件的publish里加上map_en: true publish: 出版： path_en: false path_en：false map_en: true map_en：true
> > 
> > 
> > 您好，请问这个yml文件是哪个呢
> 
> 在config文件夹里，你用哪种雷达，就在哪个里面加

哦好的，解决了，谢谢！！
