### ISSUE TITLE
Is livox_ros_driver2 required at all?

### ISSUE THREAD

**Issue by ashBabu** [hku-mars/FAST_LIO#317]
Hi 
I see [here](https://github.com/hku-mars/FAST_LIO/blob/ROS2/CMakeLists.txt#L62) that the `livox_ros_driver2` is a must for compiling FAST_LIO. I dont have a livox lidar but ouster. Do I still need livox? Or am I missing something here?

Thanks

**Comment by Ericsii** [comment]
Yes, this is following the original ros1 version FAST_LIO. You can simply put the livox_ros_driver2 package in source directory to complete the compile stage.

**Comment by satyajitghana** [comment]
or you can remove all the livox related code, mostly its the point cloud callback.
