### ISSUE TITLE
fastlio+livox

### ISSUE THREAD

**Issue by jiatianluo** [hku-mars/FAST_LIO#321]
我用mid-70激光雷达获取的数据包，为什么得不到pcd文件，且在运行时会报如下错，请问如何解决
`[ERROR] [1713618008.108650241]: Client [/laserMapping] wants topic /livox/lidar to have datatype/md5sum [livox_ros_driver/CustomMsg/e4d6829bdfe657cb6c21a746c86b21a6], but our version has [sensor_msgs/PointCloud2/1158d486dd51d683ce2f1be655c3c181]. Dropping connection.`

**Comment by JiaoxianDu** [comment]
Obvious fast_lio need /livox/lidar to have CustomMsg but Lidar publish PointCloud2, if you are using a real Lidar, you can set the output mode for CustomMsg.
