### ISSUE TITLE
Inconsistent Z position estimate in outdoor unstructured environments

### ISSUE THREAD

**Issue by Pallav1299** [hku-mars/FAST_LIO#329]
@XW-HKU @Ecstasy-EC 
Hi, thanks for the package.
I've been testing Fast LIO on a UAV for structured(indoors) and unstructured(forest) environments with Ouster OS0-32.
I've noticed inconsistencies in Z position estimate. With the same set of config params, different flights of similar behaviour give different Z estimates. 
Since we've been using the IMU onboard the damped OBC, we suspected slight changes in LIDAR->IMU Extrinsics in pitch and roll. 
Now that we've removed the dampening, we're still facing the same behaviour. 

Could you help in understanding why so?

I'm attaching plots for reference for 2 flights:
In one of the flights accel bias is linearly increasing in the direction of motion. Does it portray poor cloud registration?
![1](https://github.com/hku-mars/FAST_LIO/assets/32015105/e7031a7c-adb5-4fa8-91c5-258be1145209)
![2](https://github.com/hku-mars/FAST_LIO/assets/32015105/71046bbd-0749-48a3-adb6-6f3cc72cbe6f)

Note: 
1. We've no hardware time sync between IMU and LIDAR, due to constraints of OBC ethernet interface, which doesn't support hardware timestamping.
2. We're using gravity alignment to compensate for surfaces which're not flat. We use accelerometer to initialize the rotation.

**Comment by dawkin** [comment]
Hello @pallavbhalla, 

Facing the same issue here any tips ?
