### ISSUE TITLE
Accuracy Evaluation and Odometry Data Matching

### ISSUE THREAD

**Issue by Nitinsn29** [hku-mars/FAST_LIO#335]
Hi,

Thank you for your excellent work on LiDAR-Inertial SLAM. I have tried running both the FAST-LIO ROS1 and ROS2 versions with the MulRan Urban dataset (specifically the DCC dataset).

rosbag used
![Screenshot from 2024-06-29 12-59-13](https://github.com/hku-mars/FAST_LIO/assets/106977025/2b8c1f97-b730-46f7-9ee3-597e9630517f)

To save the odometry results, I added some code between set_posestamp(odomAftMapped.pose) and pubOdomAftMapped.publish(odomAftMapped) in the publish_odometry() function. The data format is timestamp, t.x, t.y, t.z, q.x, q.y, q.z, q.w (where t represents translation and q represents quaternion). I have converted it into the format [timestamp, R.x1, R.x2, R.x3, T.x, R.y1, R.y2, R.y3, T.y, R.z1, R.z2, R.z3, T.z] (where R represents rotation and T represents translation) to match the ground truth of the MulRan dataset. My dataset has 4500-5500 values, but the MulRan ground truth dataset has 52,402 values.

In your FAST-LIO2: Fast Direct LiDAR-Inertial Odometry research paper, you benchmarked the accuracy using the translation error. Can you help me with calculating the translation error (RMSE)? If possible, could you share the code or details on how to calculate the translation error?

Additionally, why is the odometry data 10 times less than the ground truth data? How can I match it using the nearest timestamp?

Thank you for your assistance.

Best regards,
Nitin Natarajan

**Comment by karthikbolla** [comment]
@Nitinsn29 DId you solve this issue ?
