### ISSUE TITLE
How to run FAST_LIO by using Livox and external IMU?

### ISSUE THREAD

**Issue by WN-Wolf** [hku-mars/FAST_LIO#337]
I am a beginner, if you by pass, please give me some advice, many thanks!
lidar：livox mid-70
IMU：wit JY901B

Q1: If I get a LiDAR_IMU_Init result, like this:
I want to know, how to use this result in FAST_LIO? Where to use this result?
![image](https://github.com/hku-mars/FAST_LIO/assets/75304226/498d19d6-da9e-4d98-8070-735337e024b6)

Q2: For Livox serials with external IMU
I have modified config/avia.yaml like this.
![image](https://github.com/hku-mars/FAST_LIO/assets/75304226/b5a7204b-442c-44a5-83a6-9200c06a139b)
and then run command, "roslaunch fast_lio mapping_avia.launch".

What about the next? run this command "rosbag play my_record_lidar_imu.bag"? 

How to get "my_record_lidar_imu.bag"? 
Is it recorded using this command after time synchronization? 
"rosbag record -o my_livox_wit.bag /livox/lidar /wit/imu"

**Comment by WN-Wolf** [comment]
Let me ask my question! haha!
1. How to use the Initialization_result.txt.
![image](https://github.com/user-attachments/assets/07db5609-7c79-440a-8e99-0991f340529e)
2. How to run fast_lio2
first terminal: roslaunch livox_ros_driver livox_lidar_msg.launch
second terminal: roslaunch wit_ros_imu wit_imu.launch
last terminal: roslaunch fast_lio mapping_avia.launch
pcd file path: /fast_lio2/src/FAST_LIO/PCD, then download pcl_viewer to watch pointclound.

**Comment by jongco22** [comment]
Thank you for your question ^^*

**Comment by fitzzzzzzzzz** [comment]
hi @nw-wf , i am also beginner, could you please tell me how did you get the initilization.txt result? 
i am using livox mid 360

**Comment by X-WN** [comment]
> hi @nw-wf , i am also beginner, could you please tell me how did you get the initilization.txt result? i am using livox mid 360

I have gave up using external lidar and I have bought mid-70 to run fastlio.

**Comment by fitzzzzzzzzz** [comment]
oh :/ 
I am also using mid360 now, but if I rotate two times in the same place, the graph drifts in height and position a little bit. it does not exactly match. i guess loop closure isn't working properly.

**Comment by fitzzzzzzzzz** [comment]
also can you please tell me though, how did you run this initialization script @nw-wf ? 
how are you getting these values of Initialization_result?

**Comment by X-WN** [comment]
> also can you please tell me though, how did you run this initialization script @nw-wf ? how are you getting these values of Initialization_result?

please to refer to this https://github.com/hku-mars/LiDAR_IMU_Init/issues/108#issue-2397438510

**Comment by X-WN** [comment]
> > also can you please tell me though, how did you run this initialization script @nw-wf ? how are you getting these values of Initialization_result?
> 
> please to refer to this [hku-mars/LiDAR_IMU_Init#108 (comment)](https://github.com/hku-mars/LiDAR_IMU_Init/issues/108#issue-2397438510)

and this project https://github.com/hku-mars/LiDAR_IMU_Init
