### ISSUE TITLE
Lidar rotation isn't working

### ISSUE THREAD

**Issue by er1c-cartman** [hku-mars/FAST_LIO#338]
Hi,

I have been using your excellent work, but unfortunately, I am encountering a serious issue.

To use fast_lio in my robot, I have rotated the LiDAR 180 degrees on the x-axis. However, the map appears upside down; the LiDAR point cloud is pointing at the ceiling instead of the floor.

I have modified the URDF to apply the rotation on the x-axis, but it hasn't resolved the issue.

How can I fix this error?

![image](https://github.com/user-attachments/assets/4ba301d9-b8f2-4811-853a-fb099476befe)

**Comment by er1c-cartman** [comment]
For better understanding, I'm uploading more images

![image](https://github.com/user-attachments/assets/2fbed14a-028a-4d16-96b9-da9efe1272aa)


![image](https://github.com/user-attachments/assets/afe7486f-6ca2-4db5-8103-ce07b489b94e)

And i have made a turn on xacro

  <xacro:include filename="$(find ros2_livox_simulation)/urdf/mid360.xacro" />
  <xacro:mid360 name="livox_frame" parent="base_link" topic="/livox/lidar">
    <origin xyz="0 0 0.86521" rpy="3.14 0 0"/>
  </xacro:mid360>

**Comment by IacopomC** [comment]
I think this issue may help you #284 althought it doesn't fully solves the problem
