### ISSUE TITLE
save trajectory from scan

### ISSUE THREAD

**Issue by Jaetriel** [hku-mars/FAST_LIO#34]
Hi, is there a way currently to save the trajectory from a scan in something like a pcd file like the map is saved?

**Comment by EloyAldao** [comment]
+1

**Comment by XW-HKU** [comment]
you can try to set runtime_pos_log_enable to 1，then you can find a txt here：/Log/pos_log.txt.

**Comment by ly-uuu** [comment]
> you can try to set runtime_pos_log_enable to 1，then you can find a txt here：/Log/pos_log.txt.
> 
> For the file format, please refer to dump_lio_state_to_log(FILE *fp) in src/LaserMapping.cpp.

您好，请问怎么输出类似于TUM/KITTI的数据格式呢

**Comment by wangchuanhao1231** [comment]
> > 你可以尝试将 runtime_pos_log_enable 设置为 1，然后你可以在这里找到一个 txt：/Log/pos_log.txt。
> > 文件格式请参考 src/LaserMapping.cpp 中的 dump_lio_state_to_log（FILE *fp）。
> 
> 您好，请问怎么输出类似于TUM/KITTI的数据格式呢

你好，请问你知道如何输出了吗

**Comment by Breaking-Bugs** [comment]
I know it's a bit late, but better late than never. Here are the steps to convert `pos_log.txt` from FAST-LIO into TUM trajectory format:

## 1. Enable logging in your launch file

Go to your launch file and find this line:
```xml
<param name="path_save_en" type="bool" value="0" />
```

Change the `0` to `1` to make sure `pos_log.txt` will be saved (it will appear under the `Log/` directory of the FAST-LIO workspace).

## 2. Find the rosbag start time

Run:
```bash
rosbag info your_bag_file.bag
```

Note the start time, which is the base UNIX timestamp you will need. FAST-LIO stores only relative time in `pos_log.txt`.

## 3. Convert the log to TUM format

Save the following script as `convert_poslog_to_tum.py`:

```python
import argparse
from scipy.spatial.transform import Rotation as R

def convert_pos_log_to_tum(input_file, output_file, base_time):
    with open(input_file, 'r') as fin, open(output_file, 'w') as fout:
        for line in fin:
            tokens = line.strip().split()
            if len(tokens) < 7:
                continue
                
            relative_time = float(tokens[0])
            timestamp = base_time + relative_time
            
            roll, pitch, yaw = map(float, tokens[1:4])
            tx, ty, tz = map(float, tokens[4:7])
            
            quat = R.from_euler('xyz', [roll, pitch, yaw]).as_quat()  # x, y, z, w
            qx, qy, qz, qw = quat
            
            fout.write(f"{timestamp:.6f} {tx:.6f} {ty:.6f} {tz:.6f} "
                       f"{qx:.6f} {qy:.6f} {qz:.6f} {qw:.6f}\n")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Convert FAST-LIO pos_log.txt to TUM trajectory format")
    parser.add_argument("input", help="Path to input pos_log.txt")
    parser.add_argument("output", help="Path to output trajectory_tum.txt")
    parser.add_argument("--base_time", type=float, default=1627729762.57,
                        help="Base UNIX time to add to relative timestamps (default: 1627729762.57)")
    
    args = parser.parse_args()
    convert_pos_log_to_tum(args.input, args.output, args.base_time)
```

## 4. Usage example

With default base time:
```bash
python3 convert_poslog_to_tum.py pos_log.txt trajectory_tum.txt
```

With custom base time:
```bash
python3 convert_poslog_to_tum.py pos_log.txt trajectory_tum.txt --base_time 1650000000.0
```

You can now evaluate using `evo_ape`, for example:
```bash
evo_ape tum groundtruth.txt trajectory_tum.txt
```

Let me know if anything is unclear.
