### ISSUE TITLE
How to improve the result?

### ISSUE THREAD

**Issue by WN-Wolf** [hku-mars/FAST_LIO#340]
I have obtained a indoor result now, but it isn't very ideal!
It was good at first, but there was a drift after a few seconds!
Has anyone encountered this situation? Could you give me some advice? Thanks!
first try:
![3e5fc600159640fcde5d550bbf64fbfd](https://github.com/user-attachments/assets/8894dedf-3c46-4a98-b2f7-79248fe64760)
![9879894e7850d8401ecd7c0b529ed9fc](https://github.com/user-attachments/assets/c9ef4ca9-c278-4d3b-8040-6e3799c022d7)
second try:
![a8af83a7db8ce610eea8294970d23d08](https://github.com/user-attachments/assets/82cbf39f-286f-4a8b-a450-b9bff4e1ecf9)
![ac490a79648fee71cd87f5826219ab18](https://github.com/user-attachments/assets/146f9089-6575-4204-9a79-6ddedb5bef7a)
![cbdf66280ac06712858a2a9cb0e12836](https://github.com/user-attachments/assets/6256bb76-b28a-47cf-955d-188e59e28a12)

**Comment by 20251181** [comment]
解决了吗？

**Comment by comeflywithmeeee** [comment]
Were you able to resolve it? Thanks
