### ISSUE TITLE
why “No point, skip this scan!”，“No Effective Points!”？！

### ISSUE THREAD

**Issue by txt1108** [hku-mars/FAST_LIO#342]
我的雷达时livox mid70，和维特imu ，为什么在运行fast-lio算法时，出现警告“No point, skip this scan!”，“No Effective Points!”，是不是我的pcd文件过于相同而导致的，这会不会导致重建效果不好

**Comment by cuboya** [comment]
你好，请问怎么解决的呢，我也有这个问题

**Comment by 20251181** [comment]
同问
