### ISSUE TITLE
Failed in marsim simulation

### ISSUE THREAD

**Issue by Yangrlan** [hku-mars/FAST_LIO#347]
Hi authors:
The fast-lio2 drifts when the drone begins to move in the marsim simulator. The planner I used is ego-planner and the trajectory is not aggressive. I changed to use mid360 but it still drifts. It puzzles me for a long time as I have tried before the fast-lio2 supports the simulator. And may you give me some suggestions?

**Comment by ngocquynhle** [comment]
Hi @Yangrlan 
Have you solved this problem yet?

**Comment by Yangrlan** [comment]
I found the problem today. Maybe in the current simulator, the topic of the pointcloud that fast-lio should use is "/robot_0/velodyne_points" but not the "/quad0_pcl_render_node/cloud". Because the frame of the previous one is body frame and the latter one is world frame.
