### ISSUE TITLE
Don't save map

### ISSUE THREAD

**Issue by Parkeunseok** [hku-mars/FAST_LIO#348]
It is currently in use by ubuntu 22.04 ros2 humble

The config file I set is as follows.

As you can see in the file below, the map is not saved even though "pcd_save_en" is true.

![Screenshot from 2024-08-06 15-23-48](https://github.com/user-attachments/assets/42093397-dfa7-42cc-9cac-41357bd0288d)

![Screenshot from 2024-08-06 15-24-01](https://github.com/user-attachments/assets/6c0577a9-0b24-40b2-a43e-403cd214768d)

What is the solution?

**Comment by roboticlemon** [comment]
I've had 2 problems,
1) the ROOT_DIR wasn't setting correctly if you have a non-standard directory structure. Manually hard coding this can be a quick workaround.
2) the map wouldn't save in time before SIGKILL was sent my roslaunch. You can verify if this is happening because you won't see the 
> current scan saved to /PCD/

print to screen.

**Comment by Ericsii** [comment]
In order not to be affected by the io operation of the saved map performance, I made a new ros service `map_save` with type std_srvs/Trigger. You can try manually trigger the service to save the map pointcloud to file.

**Comment by Parkeunseok** [comment]
i'm solved it thank you

**Comment by 123295** [comment]
I've meet the same problem and I can't save the pcd file, could you show me your folder structure? Thank you!

**Comment by pk30123** [comment]
I tried executing the service map_save, but i did not give any results , Can you please help on elaborating it

**Comment by pk30123** [comment]
[fastlio_mapping-1] [INFO] [1725266567.425343949] [laser_mapping]: Saving map to /home/pradheep/Documents/flio_ws/src/FAST_LIO/PCD/test.pcd...
[fastlio_mapping-1] terminate called after throwing an instance of 'pcl::IOException'
[fastlio_mapping-1]   what():  : [pcl::PCDWriter::writeBinary] Input point cloud has no data!
[ERROR] [fastlio_mapping-1]: process has died [pid 5983, exit code -6, cmd '/home/pradheep/Documents/flio_ws/install/fast_lio/lib/fast_lio/fastlio_mapping --ros-args --params-file /home/pradheep/Documents/flio_ws/src/FAST_LIO/config/ouster64.yaml --params-file /tmp/launch_params_4__njwjw'].

**Comment by arjunskumar** [comment]
@pk30123 check the size of pointcloud you are trying to save

**Comment by pk30123** [comment]
Do you know which topic i should check for the point cloud? i could see rviz building. Same dataset in ros1 docker works

**Comment by arjunskumar** [comment]
are the config same for both docker and non docker enviornment?

**Comment by pk30123** [comment]
Hi, sorry to elaborate i used docker in FASTLIO ROS1 and FASTLIO2 . the calibration matrices are the same , i could see some output in RVIZ in both but there is no saved pcd files in ROS2

**Comment by lidarmansiwon** [comment]
@pk30123 I had the same problem and error. I tried various ways to save the map.
My environment is humble and the solution was to uncomment the code below and the map was saved.

laserMapping.cpp

Uncommented the comment code at line 513.

/**************** save map ****************/
/* 1. make sure you have enough memories
/* 2. noted that pcd save will influence the real-time performences **/
if (pcd_save_en)
{
int size = feats_undistort->points.size();
PointCloudXYZI::Ptr laserCloudWorld( \
new PointCloudXYZI(size, 1));

for (int i = 0; i < size; i++)
{
RGBpointBodyToWorld(&feats_undistort->points[i], \
&laserCloudWorld->points[i]); } *pcl_wait_save += *laserCloudWorld;

 static int scan_wait_num = 0;
 scan_wait_num++;
 if (pcl_wait_save->size() > 0 && pcd_save_interval > 0 && scan_wait_num >= pcd_save_interval) { pcd_index ++;
 string all_points_dir(string(string(ROOT_DIR) + "PCD/scans_") + to_string(pcd_index) + string(".pcd"));
 pcl::PCDWriter pcd_writer;
 cout << "current scan saved to /PCD/" << all_points_dir << endl;
 pcd_writer.writeBinary(all_points_dir, *pcl_wait_save);
 pcl_wait_save->clear();
 scan_wait_num = 0;
 }
}
}

**Comment by pk30123** [comment]
Hi,

Thanks for the update. This made the map to save on Ctrl+C not on srv .

Thanks

**Comment by G7-3208** [comment]
> [fastlio_mapping-1][信息][1725266567.425343949] [laser_mapping]：正在将地图保存到 /home/pradheep/Documents/flio_ws/src/FAST_LIO/PCD/test.pcd... [fastlio_mapping-1] 在抛出 'pcl：：IOException' 实例后终止调用 [fastlio_mapping-1] what（）： ： [pcl：:P CDWriter：：writeBinary] 输入点云没有数据！ [错误] [fastlio_mapping-1]：进程已死机 [pid 5983，退出代码 -6，cmd '/home/pradheep/Documents/flio_ws/install/fast_lio/lib/fast_lio/fastlio_mapping --ros-args --params-file /home/pradheep/Documents/flio_ws/src/FAST_LIO/config/ouster64.yaml --params-file /tmp/launch_params_4__njwjw']。

Hello, I have encountered the same problem as you. How did you solve it

**Comment by lesurJ** [comment]
same error for me
