### ISSUE TITLE
Point stored in sensor position

### ISSUE THREAD

**Issue by EloyAldao** [hku-mars/FAST_LIO#35]
Dear Cris:

When I use `point_filter_num=1` and I store the PCD I get a point in the position of the sensor on all of the scans.
Is there a reason for that?
I mean, if I record the raw lidar from the sensor there is not a point in the coords 0,0,0, of the scan.

Thanks

**Comment by XW-HKU** [comment]
Maybe there is bug in preprocess.cpp, I saw this phenomenon before but looks like it has no but influence so I ignore it. I will see it after a while. If you hurry, you can try to debug the preprocess.cpp.
