### ISSUE TITLE
I need help with adjusting yaml file parameters.

### ISSUE THREAD

**Issue by lidarmansiwon** [hku-mars/FAST_LIO#356]
Hi, I am using fast_lio with ouster in humble. I am using ouster pointcloud and built-in imu, but it is showing poor mapping results. What exactly do these parameters mean, how to use them, and are there any recommended parameters for outdoor use? How should I adjust them?

/**:
    ros__parameters:
        feature_extract_enable: false
        point_filter_num: 3
        max_iteration: 3
        filter_size_surf: 0.5
        filter_size_map: 0.5
        cube_side_length: 1000.0
        runtime_pos_log_enable: false
        map_file_path: "./test.pcd"
        
     And additionally, even if we use the internal imu of ouster, do we need to calibrate the two through an external algorithm?
     Please help me,,

**Comment by juliangaal** [comment]
you're performance issues are likely due to changes in the ouster ros2 tf tree. `os_imu` now points in the opposite direction of `os_lidar`, therefore, you need to update the IMU->Lidar transformation parameters according to the output of

```
ros2 run tf2_ros tf2_echo os_imu os_lidar
```

I already did exactly this, and more, in #365
