### ISSUE TITLE
Question about discrete model in fast lio

### ISSUE THREAD

**Issue by LeisureLei** [hku-mars/FAST_LIO#36]
Thanks for your great job! I test fast lio2 on KITTI dataset and get nice results. 
But I have a question about discrete model when I read fast lio paper. 
![image](https://user-images.githubusercontent.com/32186985/125278481-6152d880-e345-11eb-9244-7686f1547beb.png)
According to formula (2) (3), we can get P_{t+1} = P_{t} + V_{t} * δt , why not P_{t+1} = P_{t} + V_{t} * δt + 1/2 * a_{t} * δt^{2}?

**Comment by XW-HKU** [comment]
Thanks for your interests. You are right. But fastlio1 uses the zero order discretion，fastlio2 uses the first order model. But they are really very similar since the imu sample time is always very tiny.

**Comment by LeisureLei** [comment]
> Thanks for your interests. You are right. Fastlio1 uses the zero order discretion，Fastlio2 uses the first order model. But they are really very similar since the imu sample time is always very tiny.

Thanks! And I have another question about the computation of mattix F_x and F_w in appendix A. Are there some materials describing specific process?

**Comment by XW-HKU** [comment]
> > Thanks for your interests. You are right. Fastlio1 uses the zero order discretion，Fastlio2 uses the first order model. But they are really very similar since the imu sample time is always very tiny.
> 
> Thanks! And I have another question about the computation of mattix F_x and F_w in appendix A. Are there some materials describing specific process?

I think the computation of the F_x and F_w would be very easy, if you regard appendix A as a simple chain-rule of partial differential. And [this paper](https://arxiv.org/pdf/2102.03804.pdf)'s appendix has a simple example for the computation of chain-rule of partial differential combining the boxplus operation, may help you.

**Comment by LeisureLei** [comment]
> > > Thanks for your interests. You are right. Fastlio1 uses the zero order discretion，Fastlio2 uses the first order model. But they are really very similar since the imu sample time is always very tiny.
> > 
> > 
> > Thanks! And I have another question about the computation of mattix F_x and F_w in appendix A. Are there some materials describing specific process?
> 
> I think the computation of the F_x and F_w would be very easy, if you regard appendix A as a simple chain-rule of partial differential. And [IKFOM](https://arxiv.org/pdf/2102.03804.pdf)'s appendix A&B has a simple example for the computation of chain-rule of partial differential combining the boxplus operation, may help you.

Thanks!

**Comment by LeisureLei** [comment]
@XW-HKU hi, I wonder what the difference  about matrix F_x and F_w between **fast lio** and **Quaternion kinematics for the error-state KF**. I try to compare them. And some parts sre same, some parts are different.

**Comment by XW-HKU** [comment]
> @XW-HKU hi, I wonder what the difference about matrix F_x and F_w between **fast lio** and **Quaternion kinematics for the error-state KF**. I try to compare them. And some parts sre same, some parts are different.

The main differences i think is using rotation matrix or quaternion.

**Comment by LeisureLei** [comment]
> > @XW-HKU hi, I wonder what the difference about matrix F_x and F_w between **fast lio** and **Quaternion kinematics for the error-state KF**. I try to compare them. And some parts sre same, some parts are different.
> 
> The main differences i think is using rotation matrix or quaternion.

Got it!

**Comment by HaisenbergPeng** [comment]
> > @XW-HKU hi, I wonder what the difference about matrix F_x and F_w between **fast lio** and **Quaternion kinematics for the error-state KF**. I try to compare them. And some parts sre same, some parts are different.
> 
> The main differences i think is using rotation matrix or quaternion.

Hi, Mr. Xu, there is a very good [blog](https://zhuanlan.zhihu.com/p/441182819) about ESKF deduction based on SO3, which is written by Dr. Gao, Xiang.  Based on his deduction, there should be no "-A(w_i*deltaT)^T*deltaT" for equation 7  in your 2021 RAL fastlio paper.
![image](https://user-images.githubusercontent.com/72208396/161683729-041cbca1-5ad5-45f7-a17a-6a172b33b552.png)
What do you think?

**Comment by ZongHengScholar** [comment]
> 
I'm also curious that it's not in the code, but it's in the paper.Again, i should be clear about the formula.

**Comment by ZongHengScholar** [comment]
> > > @XW-HKU hi, I wonder what the difference about matrix F_x and F_w between **fast lio** and **Quaternion kinematics for the error-state KF**. I try to compare them. And some parts sre same, some parts are different.
> > 
> > 
> > The main differences i think is using rotation matrix or quaternion.
> 
> Hi, Mr. Xu, there is a very good [blog](https://zhuanlan.zhihu.com/p/441182819) about ESKF deduction based on SO3, which is written by Dr. Gao, Xiang. Based on his deduction, there should be no "-A(w_i_deltaT)^T_deltaT" for equation 7 in your 2021 RAL fastlio paper. ![image](https://user-images.githubusercontent.com/72208396/161683729-041cbca1-5ad5-45f7-a17a-6a172b33b552.png) What do you think?

I'm also curious that it's not in the code, but it's in the paper.Again, i should be clear about the formula.

**Comment by zhouqiuhua** [comment]
> Thanks for your great job! I test fast lio2 on KITTI dataset and get nice results. But I have a question about discrete model when I read fast lio paper. ![image](https://user-images.githubusercontent.com/32186985/125278481-6152d880-e345-11eb-9244-7686f1547beb.png) According to formula (2) (3), we can get P_{t+1} = P_{t} + V_{t} * δt , why not P_{t+1} = P_{t} + V_{t} * δt + 1/2 * a_{t} * δt^{2}?
Hello boss, may I ask which sequences from the Kitti dataset you tested on Fast-LiO2? I tested all the sequences, but only 05, 06, 07, and 09 were successful. The others were all quite outrageous

**Comment by zhouqiuhua** [comment]
Hello boss, may I ask which sequences from the Kitti dataset you tested on Fast-LiO2? I tested all the sequences, but only 05, 06, 07, and 09 were successful. The others were all quite outrageous

**Comment by Orangeflying** [comment]
Hello boss, which sequences did you test on the KITTI dataset? I found that FAST-LIO2 has significant drift during my tests!
