### ISSUE TITLE
The odometer output is incorrect when the MID360 radar operates at a frequency of 50Hz.

### ISSUE THREAD

**Issue by JACKLiuDay** [hku-mars/FAST_LIO#375]
When I set the MID360 radar to operate at a frequency of 50Hz while running Fast LIO, the odometer output is incorrect. However, when set to a frequency of 10Hz, the odometer output is correct.

**Comment by JoLichtenfeld** [comment]
I am able to set the odometry publish rate to 100Hz by changing [this](https://github.com/hku-mars/FAST_LIO/blob/eb83a8ae838e4c1042c49229cda5e9b255402797/src/laserMapping.cpp#L939) variable. It works with my MID360 publishing point clouds at 100 Hz.
