### ISSUE TITLE
Large drift in generated map using Velodyne VLP 16

### ISSUE THREAD

**Issue by aditdoshi333** [hku-mars/FAST_LIO#40]
Hello,

Thanks for sharing such amazing work. I am using fastlio 2 for map generation using Velodyne vlp16 and intel l515 (for imu). For some scenarios, it is generating an amazing map. But for some, there is a large drift during mapping. Can you please help me if there is any fine-tuning needed for the same?

Snapshot (Scene: Car parking basement)
![Screenshot from 2021-07-16 10-11-48](https://user-images.githubusercontent.com/23434856/125893841-7c19012c-0420-42a0-8646-2fa43c9d9295.png)

**Comment by XW-HKU** [comment]
Thanks for your tests. I may need more information about this abnormal drift:

1. Was the vlp16 and L515 time synced?
2. Is the extrinsic between imu and lidar set right? I recommend to let their axis orientations be the same.
3. Was there any message drop in the data sequence? You can rostopic echo imu_topic/header to see if the timestamp are normal when when the drift happens.

**Comment by chengwei0427** [comment]
hi @aditdoshi333 ，I have a similar problem, after a thorough investigation, I found that there was no IMU data for some time.You can take a test and check it out.

**Comment by XW-HKU** [comment]
> hi @aditdoshi333 ，I have a similar problem, after a thorough investigation, I found that there was no IMU data for some time.You can take a test and check it out.

You are right, if imu drops for while, fastlio may fail, it is truely a problem we will fix in the future.

**Comment by aditdoshi333** [comment]
@XW-HKU @chengwei0427 Thanks for the update. I will check and update..
