### ISSUE TITLE
Question about the cpu consume

### ISSUE THREAD

**Issue by chengwei0427** [hku-mars/FAST_LIO#46]
Hi,Dr Xu
Thank you for the amazing work，I have a problem about the program cpu.
**my computer is Ubuntu16.04 : intel core-i7-10700F@2.9GHz*6,GeForce GTX 1660Ti/PCle/SSE2**
I have a **vlp16**, and test the data I recorded use the **mapping_velodyne.launch** with the **default parameters**,
I find that, the data processing frequency is lower than 10Hz[**Not real time**] in the first few minutes, and the CPU usage is also high.
Is this normal?
![2021-07-22 17-45-43屏幕截图](https://user-images.githubusercontent.com/20199999/126620383-0ca9ae6f-706e-4b2d-9e64-19a60716e4ed.png)

thanks.

**Comment by XW-HKU** [comment]
That's really abnormal, could you share me a piece of data?

**Comment by XW-HKU** [comment]
What happens if you set scan_publish_en in velodyne.yaml to 0?

**Comment by chengwei0427** [comment]
Hi,Dr Xu
Thanks for your reply.
I test a new data set today, the cpu is still very high(about 160%).
`What happens if you set scan_publish_en in velodyne.yaml to 0?`
The cpu is about 150% after set scan_publish_en and dense_publish_enable to 0.
`And you can try the avia datas in the readme to check the processing time for a avia scan. `
I can't access Google because of the gfw.
Here is my test dataset.
链接：https://pan.baidu.com/s/1epdYQ7_PmyQiVeD4Iw9iew 
提取码：b4qt

thanks!

**Comment by XW-HKU** [comment]
> Hi,Dr Xu
> Thanks for your reply.
> I test a new data set today, the cpu is still very high(about 160%).
> `What happens if you set scan_publish_en in velodyne.yaml to 0?`
> The cpu is about 150% after set scan_publish_en and dense_publish_enable to 0.
> `And you can try the avia datas in the readme to check the processing time for a avia scan. `
> I can't access Google because of the gfw.
> Here is my test dataset.
> 链接：https://pan.baidu.com/s/1epdYQ7_PmyQiVeD4Iw9iew
> 提取码：b4qt
> 
> thanks!

I am downloading the bag.

Maybe the cpu consume rate shown in **top** commend is not important since 100% stands for using only one core. You can use **sudo htop** to check each CPU core's usages. The more important thing is the real-time performence, the easist way to varify it is stopping the bag play too see if the fast-lio update is stop in the same time.

**Comment by XW-HKU** [comment]
> Hi,Dr Xu
> Thanks for your reply.
> I test a new data set today, the cpu is still very high(about 160%).
> `What happens if you set scan_publish_en in velodyne.yaml to 0?`
> The cpu is about 150% after set scan_publish_en and dense_publish_enable to 0.
> `And you can try the avia datas in the readme to check the processing time for a avia scan. `
> I can't access Google because of the gfw.
> ![2021-07-23 10-50-45屏幕截图](https://user-images.githubusercontent.com/20199999/126732349-50aeeb7d-f07f-4389-88e7-87e44166b536.png)
> 
> ![2021-07-23 10-55-40屏幕截图](https://user-images.githubusercontent.com/20199999/126732546-ae3f4e98-04f8-4a96-83ef-58eca4c84b7a.png)
> 
> thanks!

I already downloaded it.

And seems it consumes smaller than 10 ms in my computer (intel i9-10980HK CPU @ 2.40GHz, 16G RAM). The ave total stands for the average processing time for a LiDAR scan.

![cpu_time_check](https://user-images.githubusercontent.com/18547249/126732882-62701227-39f9-40fd-b3b1-1b34d6c65430.png)

**Comment by chengwei0427** [comment]
Hi,Dr Xu
Thanks for your reply.
It's **x86_64** after the commend **uname -p**;

**Comment by XW-HKU** [comment]
> Hi,Dr Xu
> Thanks for your reply.
> It's **x86_64** after the commend **uname -p**;
> the dependency is Eigen:3.2.92,pcl:1.9
> **Maybe something wrong with my dependency?**
> ![pc](https://user-images.githubusercontent.com/20199999/126735056-396735a8-255d-4022-8103-665c575fb162.png)
> 
> ![2021-07-23 11-42-53屏幕截图](https://user-images.githubusercontent.com/20199999/126735140-d263fb45-d30e-4a72-a4df-c1ba4ae20291.png)

May be you can try to upgrade eigen to 3.3. looks like the processing time increase is relative to the matrix computation.

**Comment by chengwei0427** [comment]
Hi,Dr Xu
The cpu consume is about 45% after update Eigen version[Eigen 3.3.6],Is this normal?
![2021-07-23 13-32-29屏幕截图](https://user-images.githubusercontent.com/20199999/126741030-47b4e746-2709-4c8a-a6f7-64200a940353.png)
Thank you very much.

**Comment by XW-HKU** [comment]
That looks very normal, and how about the processing time?

**Comment by chengwei0427** [comment]
The average processing time is around 9ms, it's amazing!
![s](https://user-images.githubusercontent.com/20199999/126752860-9518c711-5411-4bce-89cc-8b7a9903403d.png)
![t](https://user-images.githubusercontent.com/20199999/126752875-71ba3901-bcca-4d34-9b74-fbfb1d3435b3.png)

**Comment by XW-HKU** [comment]
Thanks, that's great

**Comment by chengwei0427** [comment]
Thank you for your patient reply,
 I close the issue as the questions are solved.

Thanks again
