### ISSUE TITLE
Relocalization with Saved PCD Map

### ISSUE THREAD

**Issue by David9696** [hku-mars/FAST_LIO#47]
Hi,

I have used this package to create a very good 3D map with Livox Mid lidar. With the saved PCD file, is it possible to use this package to do relocalization? Something like the following package:

https://github.com/Livox-SDK/livox_relocalization

Thanks for your great package.

David.

**Comment by kxch928925819** [comment]
我也在琢磨这个！1、如果Evo比较熟悉，可以试试 2、可以采用cloudcopare ，手动移&nbsp;
水平有限，思路而已！





------------------ Original ------------------
From: David9696 ***@***.***&gt;
Date: Sat,Jul 24,2021 2:46 PM
To: hku-mars/FAST_LIO ***@***.***&gt;
Cc: Subscribed ***@***.***&gt;
Subject: Re: [hku-mars/FAST_LIO] Relocalization with Saved PCD Map (#47)





 
Hi,
 
I have used this package to create a very good 3D map with Livox Mid lidar. With the saved PCD file, is it possible to use this package to do relocalization? Something like the following package:
 
https://github.com/Livox-SDK/livox_relocalization
 
Thanks for your great package.
 
David.

**Comment by HViktorTsoi** [comment]
> Hi,
> 
> I have used this package to create a very good 3D map with Livox Mid lidar. With the saved PCD file, is it possible to use this package to do relocalization? Something like the following package:
> 
> https://github.com/Livox-SDK/livox_relocalization
> 
> Thanks for your great package.
> 
> David.

Hi, we've implemented a simple relocalization system based on FAST_LIO, please take a look! https://github.com/HViktorTsoi/FAST_LIO_LOCALIZATION

**Comment by XW-HKU** [comment]
> > Hi,
> > I have used this package to create a very good 3D map with Livox Mid lidar. With the saved PCD file, is it possible to use this package to do relocalization? Something like the following package:
> > https://github.com/Livox-SDK/livox_relocalization
> > Thanks for your great package.
> > David.
> 
> Hi, we've implemented a simple relocalization system based on FAST_LIO, please take a look! https://github.com/HViktorTsoi/FAST_LIO_LOCALIZATION

Thank you very much! Your works are great!

**Comment by h-rover** [comment]
@HViktorTsoi Thanks for letting me know. Great work!

**Comment by David9696** [comment]
Thanks. It works like a charm.
