### ISSUE TITLE
plane estimation

### ISSUE THREAD

**Issue by LeisureLei** [hku-mars/FAST_LIO#48]
Hi @XW-HKU 
In function **h_share_model()**, what does '**s**' mean  after calculating plane parameters?
![image](https://user-images.githubusercontent.com/32186985/126952922-10b4a56c-26c6-451e-aac5-a3369a62a3b7.png)

**Comment by LeisureLei** [comment]
Is **s** to measure the measurement accuracy of LiDAR at different distances?

**Comment by XW-HKU** [comment]
> Is **s** to measure the measurement accuracy of LiDAR at different distances?

Yes.

**Comment by bruce87en** [comment]
Hi @XW-HKU What is the physical meaning of s? What does 0.9 do?
