### ISSUE TITLE
Ideal IMU Frequency and Time Synchronization

### ISSUE THREAD

**Issue by h-rover** [hku-mars/FAST_LIO#50]
Hi,

Can you please suggest an ideal IMU frequency for this package? Plus, can you please comment on achieving better time synchronization between the IMU and Livox (Mid-70) Custom Messages ?

Thanks.

**Comment by XW-HKU** [comment]
1. Actually FAST-LIO depends not much at IMU frequency, I have tested on minimum 50 Hz. But you should make sure IMU frequency is stable, that's more important.

2. About time synchronization, please refer to #44.
