### ISSUE TITLE
A question about formula 18?

### ISSUE THREAD

**Issue by zxd123** [hku-mars/FAST_LIO#51]
您好：
    我在读您的论文的时候，关于论文中的公式18有点不太懂，这个公式似乎和一般的IEKF更新不太一样？请问在哪里能找到相关的资料或文献说明呢？非常感谢您的解答！
![WXWorkCapture_1627459168787](https://user-images.githubusercontent.com/22142312/127287593-4f257198-0b25-4864-8e2b-210a6388ab09.png)

**Comment by XW-HKU** [comment]
你可以参考下我们的另外一篇文章[IKFOM](https://arxiv.org/pdf/2102.03804.pdf) 中的公式38。

You may refer to the equation 38 in [IKFOM](https://arxiv.org/pdf/2102.03804.pdf).

**Comment by zxd123** [comment]
> 你可以参考下我们的另外一篇文章[IKFOM](https://arxiv.org/pdf/2102.03804.pdf) 中的公式38。
> 
> You may refer to the equation 38 in [IKFOM](https://arxiv.org/pdf/2102.03804.pdf).

非常感谢回答！我去研读一下这篇论文！
Thank you very much for your reply! I will study this paper ASAP.

**Comment by qpc001** [comment]
> 你可以参考下我们的另外一篇文章[IKFOM](https://arxiv.org/pdf/2102.03804.pdf) 中的公式38。
> 
> You may refer to the equation 38 in [IKFOM](https://arxiv.org/pdf/2102.03804.pdf).

请问IKFOM论文中公式(35)的雅克比，为什么是 δxk+1|k 对 δxj 的[逆]雅克比？
