### ISSUE TITLE
point timestamp about VLP16

### ISSUE THREAD

**Issue by chengwei0427** [hku-mars/FAST_LIO#55]
Hi,Dr Xu
I have some problems about timestamp processing.
`added_pt.curvature = pl_orig.points[i].time / 1000.0;`  in preprocess.cpp and
`const double &pcl_end_time = pcl_beg_time + pcl_out.points.back().curvature / double(1000);` in IMU_Precessing.hpp
The point time stamp uint is  **microseconds** in your code, and the cloud per frame timestamp is seconds, is that so?
But in my vlp16 data, it looks like the point timestamp  is in seconds, the VLP driver version is 1.6.0.
![2021-08-12 10-47-14屏幕截图](https://user-images.githubusercontent.com/20199999/129130750-155d4fb0-47b8-47ea-9be9-a78735548322.png)
What is your VLP driver version? 

Thank you.

**Comment by XW-HKU** [comment]
You are right, the `added_pt.curvature` saves the offset time of each LiDAR point in **ms**, such that `pl_orig.points[i].time`'s unit should be **us**. If your data's each LiDAR point's time is not **us**, you may consider modifying the FAST-LIO or your data.

I only test in the open datasets such as [LIO-SAM](https://github.com/TixiaoShan/LIO-SAM)'s VLP-16 dataset, [UTBM](https://epan-utbm.github.io/utbm_robocar_dataset/) / [NCLT](http://robots.engin.umich.edu/nclt/) / [UrbanLoco](https://advdataset2019.wixsite.com/urbanloco) 's HDL-32E datasets. Their point time all are in **us**.
