### ISSUE TITLE
建图z轴漂移问题

### ISSUE THREAD

**Issue by maomao0220** [hku-mars/FAST_LIO#58]
首先非常感谢您开源这个代码，非常棒。
您好，我在用AVIA跑fast_Lio建图时，建立的地图不在栅格水平面上，估计出的雷达TF的Z轴会越来越高，然后越来越低，在跑自己的数据集时，看position的Z轴坐标最大13左右，最小负几，请问什么原因，有什么解决或缓解办法？？谢谢解答
![选区_146](https://user-images.githubusercontent.com/64572122/129487412-e368a5e6-cf13-4763-ad72-578c85340e9b.png)
![选区_145](https://user-images.githubusercontent.com/64572122/129487496-46471766-19f6-448a-a065-cb6e1c22dcf8.png)
![选区_148](https://user-images.githubusercontent.com/64572122/129487499-0d56fd3e-ccc9-4b4a-a5e4-7d74021ee841.png)

**Comment by maomao0220** [comment]
以及像这种建立出来的地图，对后面重定位和导航有很大的影响吗？？？？

**Comment by XW-HKU** [comment]
这个不叫漂移，只是因为world坐标系z轴不是铅锤方向，地图本身应该是正常的。

fastlio的world坐标系等于雷达初始的body xyz轴。

**Comment by maomao0220** [comment]
那您的意思是像这种建出来的地图也是可以用的吧，比如说用来导航路轨，

**Comment by maomao0220** [comment]
那您的意思是像这种建出来的地图也是可以用的吧？？？比如说用来进行导航或路轨

**Comment by maomao0220** [comment]
我用lili-om跑这个数据集时，就没有出现上述z轴的情况

**Comment by XW-HKU** [comment]
你这个问题我没法回答，导航能不能用取决于导航那边是怎么写的

**Comment by XW-HKU** [comment]
> 我用lili-om跑这个数据集时，就没有出现上述z轴

**Comment by Woy01** [comment]
> > 我用lili-om跑这个数据集时，就没有出现上述z轴的情况
> 
> 那说明fastlio的坐标系定义和liliom不一样

您好，请问fast lio的地图坐标系定义是采取第一帧雷达坐标系吗？

**Comment by XW-HKU** [comment]
> > > 我用lili-om跑这个数据集时，就没有出现上述z轴的情况
> > 
> > 
> > 那说明fastlio的坐标系定义和liliom不一样
> 
> 您好，请问fast lio的地图坐标系定义是采取第一帧雷达坐标系吗？

第一帧imu坐标系

**Comment by yxllnSLAM** [comment]
@maomao0220 你好，你这个问题解决了吗？可以私聊？v16621710962

**Comment by plumewind** [comment]
你好，
我发现了类似的问题。我的场景是一个下坡，可是地图是升高的，有什么改进方法或思路吗？我可以试试，比如imu初始对准？

![rviz_screenshot_2022_08_12-09_27_03](https://user-images.githubusercontent.com/25976399/184269199-8099f887-c87c-4fd2-949a-5e4ca31f1c18.png)
![rviz_screenshot_2022_08_12-09_29_34](https://user-images.githubusercontent.com/25976399/184269250-4e9d33ad-57d3-45be-adec-c1ff0deb1fcd.png)

**Comment by ZYQ1919** [comment]
> 



> > > > 我用lili-om跑这个数据集时，就没有出现上述z轴的情况
> > > 
> > > 
> > > 那说明fastlio的坐标系定义和liliom不一样
> > 
> > 
> > 您好，请问fast lio的地图坐标系定义是采取第一帧雷达坐标系吗？
> 
> 第一帧imu坐标系

May I ask where this is set in the source code?

**Comment by ZYQ1919** [comment]
> > > > 我用lili-om跑这个数据集时，就没有出现上述z轴的情况
> > > 
> > > 
> > > 那说明fastlio的坐标系定义和liliom不一样
> > 
> > 
> > 您好，请问fast lio的地图坐标系定义是采取第一帧雷达坐标系吗？
> 
> 第一帧imu坐标系

请问这是在源码哪里进行设置的呢？

**Comment by duyingchang** [comment]
你好，请问fastlio的坐标系是雷达坐标系还是imu坐标系？
