### ISSUE TITLE
CMake Error - Could not find a package configuration file provided by "livox_ros_driver"

### ISSUE THREAD

**Issue by lhypds** [hku-mars/FAST_LIO#6]
Cannot run catkin_make for below reason, anybody can help?

It says
Could NOT find livox_ros_driver (missing: livox_ros_driver_DIR)

I've already installed livox_ros_direver.

![Selection_001](https://user-images.githubusercontent.com/4526937/108360261-5384a580-7234-11eb-91bd-a3668ae57c2a.png)

**Comment by XW-HKU** [comment]
remember to source the livox ros driver before catkin_make: "cd xxxx && source devel/setup.bash" where xxxx is the workspace folder of livox ros driver.

**Comment by lhypds** [comment]
Thank you very much for your reply!!
