### ISSUE TITLE
extrinsic_R and extrinsic_T 会在线标定吗？

### ISSUE THREAD

**Issue by GuangZhaoZhou** [hku-mars/FAST_LIO#60]
感谢您的分享，效果真很棒
有个小问题，在读论文时候，看到激光和IMU的外参也是状态变量，那么最后从哪里可以输出这个变量呢？
因为还没时间读代码，所以就先询问下。
感谢！

**Comment by XW-HKU** [comment]
cd FAST_LIO/src/Log
python plot.py

会绘制states的变化曲线，其中就有外参
