### ISSUE TITLE
oust_handler function and blind parameter

### ISSUE THREAD

**Issue by Jaetriel** [hku-mars/FAST_LIO#64]
Hello, I am currently studying the code of FAST-LIO but I'm trying to figure out what exactly the blind parameter does and what this check is in the lidar handler functions: `if (range < blind) continue;` . Is it a way to check if the point is in the minimum range of the lidar or is it something else? Thanks in advance for explaining.

**Comment by XW-HKU** [comment]
**blind** is the square of minimum distance.

**Comment by Jaetriel** [comment]
okay, thank you, issue can be closed I think
