### ISSUE TITLE
No Effective Points!

### ISSUE THREAD

**Issue by David9696** [hku-mars/FAST_LIO#67]
Hi,

May I know under what situation would the fastlio package report the following warning?

No Effective Points!

Once this warning is shown, the estimated  Odometry would grow exponentially.

Hope you could enlighten me. Thanks

**Comment by XW-HKU** [comment]
> Hi,
> 
> May I know under what situation would the fastlio package report the following warning?
> 
> No Effective Points!
> 
> Once this warning is shown, the estimated Odometry would grow exponentially.
> 
> Hope you could enlighten me. Thanks

There are several conditions may lead to the  _No Effective Points!_ warning:

1. most of the points are in a very tiny space (the parameter blind controls the minimum distance fast-lio use).
2. too less points from lidar.
3. degeneration happened for a while.

**Comment by David9696** [comment]
Hi,

Thanks for your enlightenment.

1. Is it meant that I have to increase the parameter blind? Currently, it is set to 0.5.
2. This error happened when I was mapping a small room with four walls. Is it what you refer as less point? Also, would decrease the parameters of "filter_size_surf" and "filter_size_map" help? Currently, they are set as 0.5.
3. What do you meant by degeneration? Could enlighten more?

Thanks for your great helps.

**Comment by Stblacq** [comment]
I have this same issue , please has anyone manged to solve it

**Comment by Shamiikebob** [comment]
Same issue here. It seems that FASTLIO produces this issue when the data gathered is too large for the data buffer. I am using a 3D which means the number of points will always be large. Yet, I still get this isssue.

**Comment by XXLiu-HNU** [comment]
I also encountered this problem, but it didn't happen often. Sometimes it would happen 2-3 times in a day's experiment, and restarting the radar driver and algorithm would restore it to normal.
