### ISSUE TITLE
Online Georeference

### ISSUE THREAD

**Issue by swarmt** [hku-mars/FAST_LIO#7]
Hi!

This is not an issue with the library, more of a general question. Could you suggest how I would integrate GPS for online georeferencing? 

Ideally there would be a transform for the point cloud that is in UTM coordinates.

Any help would be appreciated.

**Comment by XW-HKU** [comment]
Integration of GPS is a sensor fusion problem, there are a lot of works about gps fusion. For the fusion between FAST-LIO and GPS, you may need to read our paper and fully understand the ekf algorithm in FAST-LIO. The fusion of gps is easy to be achieved in the EKF framework.

**Comment by swarmt** [comment]
Thanks!

**Comment by swarmt** [comment]
Are you able to provide an example?
