### ISSUE TITLE
 IMU  offset on avia_indoor_quick_shake_example1 and avia_indoor_quick_shake_example2

### ISSUE THREAD

**Issue by Camilochiang** [hku-mars/FAST_LIO#70]
Hei.

In both of your example avia_indoor_quick_shake_example1 and avia_indoor_quick_shake_example2, there is an offset in the linear_acceleration.z of 0.99 and -.98 respectively. When this offset is corrected, FAST_LIO do not converge and loose track of the position, so the point cloud do not match.  See below

![Screenshot from 2021-09-09 09-45-57](https://user-images.githubusercontent.com/48471579/132645118-12c4f485-b6c8-43bd-a503-5cc67fd15f13.png)

1. Do you know if this offset was set it by default (either 1 or -1) by Livox?
2.  Do you know if livox is pre-processing/filtering the IMU values before publishing it?
3.  I have an external BMI088 + mid70 and I'm correcting by the factory offset, so I'm afraid that FAST_LIO may have this problem with external IMUs.  So far I have only tried in a fix position and it works (as at the beginning of the bag example_1), but once that I start moving , I guess that I will have the same issue.
4. Also just to confirm, in which units is FAST_LIO imu data working: m s-1 and dgs  if im correct, no?

Greetings.

**Comment by XW-HKU** [comment]
the imu unit in livox lidar is g，1g is around 9.8m /s2. FAST LIO automatically support different units. but It should be noted that imu is measuring the total acceleration except for the gravity. so when lidar is steady at a point, the imu will measure the support force which is the negative of gravity, that is exactly the offset 0.99 you mentioned.

**Comment by Camilochiang** [comment]
Thanks for the quickly answer. 
What about the angular velocity ? Does FAST_LIO use rad s-1 as ROS recommend or dps?

Thanks!

**Comment by XW-HKU** [comment]
angular velocity must be in unit rad / s.

**Comment by Camilochiang** [comment]
Hei thanks!

Great. I will mark the topic as closed

**Comment by mohsenhadadi** [comment]
Hi everyone I have a similar problem with loosing track ,
When I use Fast-Lio for Livox Horizon mounted at a 90 degrees perpendicular to my IMU's Y axis ,I encountered the following errors that I have attached. Please explain a little more about the parameters that I highlighted
, I only encounter such a problem when I change livox angle related to my IMU angle downwards among Y axis ,
anybody can help me solving this problem??
![config2](https://user-images.githubusercontent.com/96223813/146344718-f1309606-a54b-47fc-b509-7052d5f752f4.JPG)
![scan](https://user-images.githubusercontent.com/96223813/146344724-d6cd1bed-f1f4-4fe0-a7f2-7b5d9d747166.JPG)
![Untitled](https://user-images.githubusercontent.com/96223813/146344725-2909d54c-618a-46d8-af7f-08228b435df7.png)

much appreciated,
