### ISSUE TITLE
Use of external odometry with Livox Avia

### ISSUE THREAD

**Issue by aditdoshi333** [hku-mars/FAST_LIO#73]
Hello @XW-HKU ,

Thank you for sharing such amazing work. I am experiencing large odometry drifts while using livox avia with inbuilt IMU. I have not changed anything in avia.yml (https://github.com/hku-mars/FAST_LIO/blob/main/config/avia.yaml).

I want to try Fastlio 2 with livox avia and real sense t265 for odometry. Is there any way to use external odometry provided by t265 realsense.  If yes can you please guide me to where are the changes required for the same?

Thank you.

**Comment by XW-HKU** [comment]
Sorry, I think it may be difficult to achieve this. Maybe you can just write a node to project the lidar point using the odometry from t265.
