### ISSUE TITLE
what is the principle of judging Surf and Edge in ‘give_feature’？

### ISSUE THREAD

**Issue by qian5683** [hku-mars/FAST_LIO#75]
Thank you for your good work.  I want to know  what is the principle of judging Surf and Edge in ‘give_feature’？I read it， but can't understand. Cloud you give me some guidance？

**Comment by XW-HKU** [comment]
That function is working for the feature extraction. But in the default configuration of FAST-LIO2, the feature extraction is disabled through the parameter **feature_extract_enable**.

**Comment by Ecstasy-EC** [comment]
Issue closed as no more activity or question appeared.
