### ISSUE TITLE
关于您提出的卡尔曼增益计算公式

### ISSUE THREAD

**Issue by dongfangzhou1108** [hku-mars/FAST_LIO#79]
我看您fast lio第一篇文章中提出的基于状态维度（而不是观测维度）的卡尔曼增益计算，和msckf的卡尔曼增益计算方式有一个共同点，都是通过避开计算基于观测维度矩阵的逆来降低计算量。msckf是通过左乘观测零空间矩阵，在保留观测约束的同时避免求其逆。请问，这两个思路有什么联系吗？多谢！

**Comment by XW-HKU** [comment]
这两个思路不太一样，msckf是利用可观矩阵筛选掉一部分特征点，进而减少state 维度。fastlio只是对 Kalman Gain 进行了数学等价。

**Comment by Ecstasy-EC** [comment]
Issue closed since no more activities or questions appeared

**Comment by Psyclonus2887** [comment]
感觉MSCKF的左乘零空间是为了把路标位置约束转移到姿态上，之后进行QR分解才是用来降维的
