### ISSUE TITLE
Is there any method to reduce the noise and increase the density of the points

### ISSUE THREAD

**Issue by lhypds** [hku-mars/FAST_LIO#8]
We recently started using AVIA devices.
We tried to Play use Livox Viewer and set the frame time to 3000ms, the output is below.

![image](https://user-images.githubusercontent.com/4526937/111114243-4f834380-85a6-11eb-95c5-1677310ca2b5.png)

We found some noise points, is there any way to reduce the noise points?
![image](https://user-images.githubusercontent.com/4526937/111114226-498d6280-85a6-11eb-9ec8-42cd7f03ba27.png)

Any anther question is, is there any way to increase the points' density?
Thank you.

**Comment by XW-HKU** [comment]
Feasture extraction may reduce the noise points but also decrease the point density.
