### ISSUE TITLE
RGB color map 

### ISSUE THREAD

**Issue by aditdoshi333** [hku-mars/FAST_LIO#80]
Hello,

Thanks for sharing such amazing work. I wanted to know is it possible to map rgb photo with the generated map by Fast Lio 2. I did the extrinsic calibration between lidar and camera using (https://github.com/hku-mars/livox_camera_calib). But I am not able to understand where I can do the changed to get the rgb map. Can you please throw some light for the same?

Thank you

**Comment by FPSychotic** [comment]
> Hello,
> 
> Thanks for sharing such amazing work. I wanted to know is it possible to map rgb photo with the generated map by Fast Lio 2. I did the extrinsic calibration between lidar and camera using (https://github.com/hku-mars/livox_camera_calib). But I am not able to understand where I can do the changed to get the rgb map. Can you please throw some light for the same?
> 
> Thank you

Hi could read that you got it work and you made a fork with it, could you please tell me how use your fork or get the rgb Im very interested, thanks.
