### ISSUE TITLE
Drifting  - Reasons why the algorithm may drift.

### ISSUE THREAD

**Issue by Camilochiang** [hku-mars/FAST_LIO#82]
Im testing your code with a MID 70 + external IMU (BMI088, same orientation and similar location as in AVIA).
In some cases the algorithm just drift appart, as for example in the attached bag after aprox 20 seconds of good matching. 
Any idea why this could be happening?
![Screenshot from 2021-09-30 09-33-00](https://user-images.githubusercontent.com/48471579/135408146-59743404-fcec-47a3-b8f5-d3263ed6da75.png)

Ps: you can find the ROSBAG and configuration files [here](https://drive.google.com/drive/folders/1wVugljpp0x9cHzMQdfczS47NgpD5DiXl?usp=sharing):

**Comment by Camilochiang** [comment]
![Screenshot from 2021-09-30 09-43-50](https://user-images.githubusercontent.com/48471579/135411513-3f008057-d9cd-4812-98a9-af0ab6cb12af.png)

**Comment by XW-HKU** [comment]
The environment seems to be a degeneration scene.

**Comment by Camilochiang** [comment]
What conditions/environments may generate this ? : Too many objects close to the LIDAR ? to little ones?

**Comment by XW-HKU** [comment]
If LiDAR only watches one or two large surfaces (for example only face
floor or ground), LiDAR cannot locate itself.

**Comment by Camilochiang** [comment]
OK! That means that the algorithm do not work in open spaces so well . I guess that this problem should not happen with R2Live as the camera may help no?

Thank in any case!

**Comment by XW-HKU** [comment]
It is not about open space. The LiDAR cannot be put only facing the wall or ground.

Of course camera will help.

**Comment by maomao0220** [comment]
在程序中，哪部分的代码会标志着程序“飞”了？
