### ISSUE TITLE
imu_rate

### ISSUE THREAD

**Issue by antun008** [hku-mars/FAST_LIO#86]
When I recording with livox_ros_driver (with livox AVIA), what happens if don't change in file livox_lidar_config.json next parameter? "imu_rate: 0"
![image](https://user-images.githubusercontent.com/49721808/136830104-fd790192-b857-418a-921d-80cc7d682a08.png)
![image](https://user-images.githubusercontent.com/49721808/136831773-a345523b-03b1-477c-b328-82d9807ad71d.png)

Because I forgot to change "imu_rate" from 0 to 1, but it still record me **/livox/imu**. And now I don't now is this dataset from /livox/imu good or not, because imu rate was set on 0 during recording. And then I asking you, what is a difference if I put imu_rate = 1, or to zero?

![image](https://user-images.githubusercontent.com/49721808/136830537-d2879268-e78a-4ba7-aa89-1d4888555a4d.png)

**Comment by rahulsharma11** [comment]
Hi,
Same issue and doubt here also.

Anyone can suggest this?
Thanks
