### ISSUE TITLE
XSens IMU的具体型号？

### ISSUE THREAD

**Issue by CogmanCVN** [hku-mars/FAST_LIO#90]
你好，请问FAST-LIO 采用的XSens IMU设备的具体型号能否告知？
是XSens MTi10系列还是XSens MTi100系列？？

谢谢~

**Comment by kxch928925819** [comment]
贵的当然好，但是从算法上来看，港科大团队的程序，对imu的不过于依赖，我的mti-300 烧了。现在用3dm-gx3-25，二手的！

**Comment by zyx-99** [comment]
> 贵的当然好，但是从算法上来看，港科大团队的程序，对imu的不过于依赖，我的mti-300 烧了。现在用3dm-gx3-25，二手的！

您好，我手里有一个3dm gx5 25，想像您问一下这个IMU在设置外参时候应该如何设置呢？我看lidar的XYZ轴所对应的欧拉角和IMU对应的欧拉角并不是一致的，所以不知道应该如何标定。如果您方便可以发邮件向您请教一下嘛。
zyx990531@163.com 谢谢
