### ISSUE TITLE
Some questions about plane and edge extraction.

### ISSUE THREAD

**Issue by h-k8888** [hku-mars/FAST_LIO#92]
Thank you for your excellent work. These are some questions about plane and edge extraction. 

- 1

What is the geometric principle of the function  
`void Preprocess::give_feature(pcl::PointCloud<PointType> &pl, vector<orgtype> &types)`
https://github.com/hku-mars/FAST_LIO/blob/d0a877db69f569964697e1135e1fcb42aae9b3f2/src/preprocess.cpp#L434
 Is there a reference paper？

- 2

```
Preprocess::Preprocess()  :feature_enabled(0), lidar_type(AVIA), blind(0.01), point_filter_num(1)
{
...
  disA = 0.01;
  disA = 0.1; // B?
...
```
https://github.com/hku-mars/FAST_LIO/blob/d0a877db69f569964697e1135e1fcb42aae9b3f2/src/preprocess.cpp#L13
https://github.com/hku-mars/FAST_LIO/blob/d0a877db69f569964697e1135e1fcb42aae9b3f2/src/preprocess.cpp#L14

any mistakes about disA and disB？

Thank you very much for your answer.

**Comment by h-k8888** [comment]
> actually，the feature extraction function is only for reference，in most of condition, we recommend disabling the feature extraction.
I am very interested in feature extraction, but it is difficult to understand the geometric principle only through the code. , it will be very helpful，if you can provide references.

**Comment by h-k8888** [comment]
> actually，the feature extraction function is only for reference，in most of condition, we recommend disabling the feature extraction.

I am very interested in feature extraction, but it is difficult to understand the geometric principle only through the code. It will be very helpful，if you can provide references.

**Comment by smileyenot983** [comment]
> > actually，the feature extraction function is only for reference，in most of condition, we recommend disabling the feature extraction.
> 
> I am very interested in feature extraction, but it is difficult to understand the geometric principle only through the code. It will be very helpful，if you can provide references.

As i remember features are same as in LOAM or LIO_SAM papers(edge features and surface features), in paper they mention them as features with high and low local smoothness, the exact formula is in LOAM paper
