### ISSUE TITLE
Velodyne HDL-32E Rosbag

### ISSUE THREAD

**Issue by toshi427** [hku-mars/FAST_LIO#93]
Thank you for sharing such amazing work. 

I created the environment by looking at README.md. 4.1 Livox Avia Rosbag worked fine, but 4.2 Velodyne HDL-32E Rosbag "20130110.bag" did not show the point cloud in Rviz.  My environment was created as follows.

Ubuntu = > 18.04
PCL and Eigen = > default
livox_ros_driver => melodic

I had to use "catkin_make -j" to build because "catkin_make" gave me an error.

Is this a failure in building the environment, or is there a file I need to configure?

 I hope you can help me. Thank you very much .

**Comment by SabraHashemi** [comment]
i have the same problem
