### ISSUE TITLE
Transformation matrix for mapping raw point cloud to final map

### ISSUE THREAD

**Issue by aditdoshi333** [hku-mars/FAST_LIO#99]
Hello,

For a project I need to remap the raw point cloud to final map. Currently I am dumping every livox point cloud in `sync_packages` from `Measures.lidar`. I tried saving /Odometry information from fastlio and then using transformation matrix from that to align raw point cloud to final point cloud but there is still some offset. Are you saving any final transformation matrix in any variable? I know this is off topic but any help is appreciated. 

Thank you

**Comment by squirreljj** [comment]
> 

hello friend,have you solve this problem?I aslo want to find the rotation and translation between every raw points and map.In laserMapping document ,I find tanslation and rotation between imu and map,but i fing it still have some offset ,can we contant each other ,my wx is superior1369,my email:1097939212@qq.com
